version: "3"

services:
  frontend:
    image: crccheck/hello-world:latest
    networks:
      hivepaas_net:
        aliases:
          - project_a_frontend
      local_net:
    ports:
      - target: 80 # Container port
        published: 8000 # Host port
        protocol: tcp
        mode: host
    deploy:
      labels:
        - "hivepaas.app.key=frontend"
        - "hivepaas.app.name=frontend"
    logging:
      driver: local
      options:
        max-size: 50m
        compress: "true"

  backend:
    image: crccheck/hello-world:latest
    networks:
      hivepaas_net:
        aliases:
          - project_a_backend
      local_net:
    deploy:
      labels:
        - "hivepaas.app.key=backend"
        - "hivepaas.app.name=backend"
    logging:
      driver: local
      options:
        max-size: 50m
        compress: "true"

  db:
    image: crccheck/hello-world:latest
    networks:
      hivepaas_net:
        aliases:
          - project_a_db
      local_net:
    deploy:
      labels:
        - "hivepaas.app.key=db"
        - "hivepaas.app.name=db"
    logging:
      driver: local
      options:
        max-size: 50m
        compress: "true"

networks:
  hivepaas_net:
    external: true
  local_net:
    driver: overlay
    attachable: true
