package main

import (
	"fmt"
	"path/filepath"
	"sort"
	"strings"
)

// orphanExemptPrefixes are ids that legitimately have no Go source.
//
// ERR_VLD_* is generated by the validation library from validator rule names
// and reaches translation through vld.SetCustomKey at runtime.
var orphanExemptPrefixes = []string{"ERR_VLD_"}

// finding is one problem to report.
type finding struct {
	Where string
	Msg   string
}

func check(uses []codeUse, entries []messageEntry, fileNames []string) []finding {
	var findings []finding

	translated := map[string][]string{} // id -> files defining it
	for _, e := range entries {
		translated[e.ID] = append(translated[e.ID], e.File)
	}

	// 1. every code used in Go has a translation.
	firstUse := map[string]codeUse{}
	for _, u := range uses {
		if _, seen := firstUse[u.Code]; !seen {
			firstUse[u.Code] = u
		}
	}
	for _, code := range sortedKeys(firstUse) {
		if len(translated[code]) > 0 {
			continue
		}
		u := firstUse[code]
		where := u.Pos.Filename
		if u.Pos.Line > 0 {
			where = fmt.Sprintf("%s:%d", u.Pos.Filename, u.Pos.Line)
		}
		findings = append(findings, finding{
			Where: where,
			Msg:   fmt.Sprintf("%s has no translation in any message file", code),
		})
	}

	// 2. no id is defined in two different files.
	for _, id := range sortedKeys(translated) {
		files := uniqueSorted(translated[id])
		if len(files) < 2 {
			continue
		}
		findings = append(findings, finding{
			Where: files[0],
			Msg: fmt.Sprintf("%s is defined in %d files (%s); the last one loaded wins, silently",
				id, len(files), strings.Join(files, ", ")),
		})
	}

	// 3. no translation is orphaned.
	used := map[string]bool{}
	for _, u := range uses {
		used[u.Code] = true
	}
	for _, id := range sortedKeys(translated) {
		if used[id] || exemptFromOrphanCheck(id) {
			continue
		}
		findings = append(findings, finding{
			Where: translated[id][0],
			Msg:   fmt.Sprintf("%s is translated but appears in no Go source", id),
		})
	}

	// 4. every message file name yields a language go-i18n can resolve.
	for _, name := range fileNames {
		if tag, ok := languageOfFile(filepath.Base(name)); !ok {
			findings = append(findings, finding{
				Where: name,
				Msg: fmt.Sprintf("file name gives language %q, which does not resolve;"+
					" name it <domain>.<lang>.toml", tag),
			})
		}
	}

	return findings
}

func exemptFromOrphanCheck(id string) bool {
	for _, p := range orphanExemptPrefixes {
		if strings.HasPrefix(id, p) {
			return true
		}
	}
	return false
}

func sortedKeys[V any](m map[string]V) []string {
	keys := make([]string, 0, len(m))
	for k := range m {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	return keys
}

func uniqueSorted(in []string) []string {
	seen := map[string]bool{}
	out := make([]string, 0, len(in))
	for _, s := range in {
		if seen[s] {
			continue
		}
		seen[s] = true
		out = append(out, s)
	}
	sort.Strings(out)
	return out
}
