package main

import (
	"fmt"
	"path/filepath"
	"sort"
	"strings"
)

// orphanExemptPrefixes are ids that legitimately have no Go source.
//
// ERR_VLD_* is generated by the validation library from validator rule names
// and reaches translation through vld.SetCustomKey at runtime.
var orphanExemptPrefixes = []string{"ERR_VLD_"}

// finding is one problem to report.
type finding struct {
	Where string
	Msg   string
}

// check runs the checks that need no identifier counts. checkAll adds the one
// that does.
func check(uses []codeUse, entries []messageEntry, fileNames []string) []finding {
	var findings []finding

	translated := map[string][]string{} // id -> files defining it
	for _, e := range entries {
		translated[e.ID] = append(translated[e.ID], e.File)
	}

	// 1. every code used in Go has a translation.
	firstUse := map[string]codeUse{}
	for _, u := range uses {
		if _, seen := firstUse[u.Code]; !seen {
			firstUse[u.Code] = u
		}
	}
	for _, code := range sortedKeys(firstUse) {
		if len(translated[code]) > 0 {
			continue
		}
		u := firstUse[code]
		where := u.Pos.Filename
		if u.Pos.Line > 0 {
			where = fmt.Sprintf("%s:%d", u.Pos.Filename, u.Pos.Line)
		}
		findings = append(findings, finding{
			Where: where,
			Msg:   fmt.Sprintf("%s has no translation in any message file", code),
		})
	}

	// 2. no id is defined in two different files.
	for _, id := range sortedKeys(translated) {
		files := uniqueSorted(translated[id])
		if len(files) < 2 {
			continue
		}
		findings = append(findings, finding{
			Where: files[0],
			Msg: fmt.Sprintf("%s is defined in %d files (%s); the last one loaded wins, silently",
				id, len(files), strings.Join(files, ", ")),
		})
	}

	// 3. no translation is orphaned.
	used := map[string]bool{}
	for _, u := range uses {
		used[u.Code] = true
	}
	for _, id := range sortedKeys(translated) {
		if used[id] || exemptFromOrphanCheck(id) {
			continue
		}
		findings = append(findings, finding{
			Where: translated[id][0],
			Msg:   fmt.Sprintf("%s is translated but appears in no Go source", id),
		})
	}

	// 4. every message file name yields a language go-i18n can resolve.
	for _, name := range fileNames {
		if tag, ok := languageOfFile(filepath.Base(name)); !ok {
			findings = append(findings, finding{
				Where: name,
				Msg: fmt.Sprintf("file name gives language %q, which does not resolve;"+
					" name it <domain>.<lang>.toml", tag),
			})
		}
	}

	return findings
}

func exemptFromOrphanCheck(id string) bool {
	for _, p := range orphanExemptPrefixes {
		if strings.HasPrefix(id, p) {
			return true
		}
	}
	return false
}

func sortedKeys[V any](m map[string]V) []string {
	keys := make([]string, 0, len(m))
	for k := range m {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	return keys
}

func uniqueSorted(in []string) []string {
	seen := map[string]bool{}
	out := make([]string, 0, len(in))
	for _, s := range in {
		if seen[s] {
			continue
		}
		seen[s] = true
		out = append(out, s)
	}
	sort.Strings(out)
	return out
}

// checkAll runs every check, including the one that needs to know how often each
// declaring identifier is referenced.
func checkAll(
	uses []codeUse,
	entries []messageEntry,
	fileNames []string,
	identUses map[string]int,
) []finding {
	findings := check(uses, entries, fileNames)

	// 5. a code bound to a name nothing refers to.
	//
	// A declaration binds its name once, so a count of one means the constant is
	// declared and never used: the product cannot raise it, and its translation
	// ships for a message no caller can produce. Codes that bind no identifier -
	// the ones reached as bare strings - cannot be judged this way and are left
	// alone.
	seen := map[string]bool{}
	for _, u := range uses {
		if !u.Declared || u.Ident == "" || seen[u.Code] {
			continue
		}
		seen[u.Code] = true
		if identUses[u.Ident] > 1 {
			continue
		}
		where := u.Pos.Filename
		if u.Pos.Line > 0 {
			where = fmt.Sprintf("%s:%d", u.Pos.Filename, u.Pos.Line)
		}
		findings = append(findings, finding{
			Where: where,
			Msg: fmt.Sprintf("%s is declared as %s but %s is never referenced;"+
				" nothing can raise it", u.Code, u.Ident, u.Ident),
		})
	}

	sortFindings(findings)
	return findings
}

func sortFindings(findings []finding) {
	sort.Slice(findings, func(i, j int) bool {
		if findings[i].Where != findings[j].Where {
			return findings[i].Where < findings[j].Where
		}
		return findings[i].Msg < findings[j].Msg
	})
}
