main:
  dialect: postgres
  datasource: postgres://${LP_DB_USER}:${LP_DB_PASSWORD}@${LP_DB_HOST}:${LP_DB_PORT}/${LP_DB_DB_NAME}?sslmode=disable
  dir: localpaas_app/db/migrations
  table: migrations

development:
  dialect: postgres
  datasource: postgres://localpaas:abc123@localhost:35432/localpaas?sslmode=disable
  dir: localpaas_app/db/migrations
  table: migrations
