package specserviceimpl

import (
	"context"
	"slices"

	"github.com/hivepaas/hivepaas/hivepaas_app/base"
	"github.com/hivepaas/hivepaas/hivepaas_app/entity"
	"github.com/hivepaas/hivepaas/hivepaas_app/service/specservice/specmodel"
)

const maxPort = 65535

func (s *service) buildKind(_ context.Context, state *buildState) error {
	block := specmodel.BlockSettingsKind
	kind := &entity.AppKindSettings{}
	body := state.req.Doc.Settings[specmodel.SingletonBlockName(base.SettingTypeAppKind)]
	if err := decodeBlock(block, body, kind); err != nil {
		return err
	}
	if !slices.Contains(base.AllAppCategories, kind.Category) {
		return invalidBlock(block, "category %q is not one of %v", kind.Category, base.AllAppCategories)
	}
	return state.addSetting(base.SettingTypeAppKind, entity.CurrentAppKindSettingsVersion, false, kind)
}

func (s *service) buildEnvVars(_ context.Context, state *buildState) error {
	block := specmodel.BlockSettingsEnvVars
	envVars := &entity.EnvVars{}
	body := state.req.Doc.Settings[specmodel.SingletonBlockName(base.SettingTypeEnvVar)]
	if err := decodeBlock(block, body, envVars); err != nil {
		return err
	}

	seen := map[string]bool{}
	for i, env := range envVars.Data {
		switch {
		case env == nil || env.Key == "":
			return invalidBlock(block, "data[%d] has no key", i)
		case env.IsSystem:
			return invalidBlock(block, "%s: system variables are generated by HivePaaS, not declared", env.Key)
		case !base.IsAppRuntimeEnvAllowed(env.Key):
			return invalidBlock(block, "%s is reserved for HivePaaS", env.Key)
		case seen[env.Key]:
			return invalidBlock(block, "%s is declared twice", env.Key)
		}
		seen[env.Key] = true
	}
	return state.addSetting(base.SettingTypeEnvVar, entity.CurrentEnvVarsVersion, true, envVars)
}

func (s *service) buildRouting(_ context.Context, state *buildState) error {
	block := specmodel.BlockSettingsRouting
	routing := &entity.AppRoutingSettings{}
	body := state.req.Doc.Settings[specmodel.SingletonBlockName(base.SettingTypeAppRouting)]
	if err := decodeBlock(block, body, routing); err != nil {
		return err
	}
	if routing.Port < 0 || routing.Port > maxPort {
		return invalidBlock(block, "port %d is out of range", routing.Port)
	}
	return state.addSetting(base.SettingTypeAppRouting, entity.CurrentAppRoutingSettingsVersion, true, routing)
}
