package specserviceimpl

import (
	"context"
	"maps"
	"slices"
	"strings"

	"github.com/hivepaas/hivepaas/hivepaas_app/base"
	"github.com/hivepaas/hivepaas/hivepaas_app/entity"
	"github.com/hivepaas/hivepaas/hivepaas_app/service/specservice/specmodel"
)

const maxPort = 65535

func (s *service) buildKind(_ context.Context, state *buildState) error {
	block := specmodel.BlockSettingsKind
	kind := &entity.AppKindSettings{}
	body := state.req.Doc.Settings[specmodel.SingletonBlockName(base.SettingTypeAppKind)]
	if err := decodeBlock(block, body, kind); err != nil {
		return err
	}
	if !slices.Contains(base.AllAppCategories, kind.Category) {
		return invalidBlock(block, "category %q is not one of %v", kind.Category, base.AllAppCategories)
	}
	return state.addSetting(base.SettingTypeAppKind, entity.CurrentAppKindSettingsVersion, false, kind)
}

func (s *service) buildEnvVars(_ context.Context, state *buildState) error {
	block := specmodel.BlockSettingsEnvVars
	envVars := &entity.EnvVars{}
	body := state.req.Doc.Settings[specmodel.SingletonBlockName(base.SettingTypeEnvVar)]
	if err := decodeBlock(block, body, envVars); err != nil {
		return err
	}

	seen := map[string]bool{}
	for i, env := range envVars.Data {
		switch {
		case env == nil || env.Key == "":
			return invalidBlock(block, "data[%d] has no key", i)
		case env.IsSystem:
			return invalidBlock(block, "%s: system variables are generated by HivePaaS, not declared", env.Key)
		case !base.IsAppRuntimeEnvAllowed(env.Key):
			return invalidBlock(block, "%s is reserved for HivePaaS", env.Key)
		case seen[env.Key]:
			return invalidBlock(block, "%s is declared twice", env.Key)
		}
		seen[env.Key] = true
	}
	return state.addSetting(base.SettingTypeEnvVar, entity.CurrentEnvVarsVersion, true, envVars)
}

func (s *service) buildRouting(_ context.Context, state *buildState) error {
	block := specmodel.BlockSettingsRouting
	routing := &entity.AppRoutingSettings{}
	body := state.req.Doc.Settings[specmodel.SingletonBlockName(base.SettingTypeAppRouting)]
	if err := decodeBlock(block, body, routing); err != nil {
		return err
	}
	if routing.Port < 0 || routing.Port > maxPort {
		return invalidBlock(block, "port %d is out of range", routing.Port)
	}
	if err := normalizeRoutingDomains(block, routing); err != nil {
		return err
	}
	return state.addSetting(base.SettingTypeAppRouting, entity.CurrentAppRoutingSettingsVersion, true, routing)
}

// normalizeRoutingDomains drops the domains an app was created without.
//
// A template names its address through a parameter, and that parameter is
// optional: somebody creating the app before pointing DNS at it leaves it empty,
// and the placeholder resolves to nothing. Dropping the entry here is what lets
// the template say it once, with no condition around it, and still describe both
// cases. An app left with no domain is not exposed publicly either, because
// there is no address for that to mean.
func normalizeRoutingDomains(block specmodel.Block, routing *entity.AppRoutingSettings) error {
	kept := make([]*entity.AppDomain, 0, len(routing.Domains))
	for i, domain := range routing.Domains {
		if domain == nil || strings.TrimSpace(domain.Domain) == "" {
			continue
		}
		domain.Domain = strings.ToLower(strings.TrimSpace(domain.Domain))
		if strings.HasPrefix(domain.Domain, "*.") {
			return invalidBlock(block, "domains[%d]: %s is what a certificate covers, not an address"+
				" a request arrives at", i, domain.Domain)
		}
		if domain.Protocol == "" {
			domain.Protocol = base.NetworkProtocolHTTP
		}
		kept = append(kept, domain)
	}
	routing.Domains = kept
	if len(kept) == 0 {
		routing.ExposePublicly = false
	}
	return nil
}

// buildSecrets and buildConfigFiles build the two collection blocks. Each entry
// is keyed by the name its setting takes, which is also what a secret is
// referred to by - ${THAT_KEY} in an environment variable - and what a config
// file is called. A body may repeat the key, and disagreeing with it is refused
// rather than resolved: one of the two would be silently ignored.
func (s *service) buildSecrets(_ context.Context, state *buildState) error {
	block := specmodel.BlockSettingsSecrets
	entries, _ := state.req.Doc.Settings[specmodel.CollectionBlockName(base.SettingTypeSecret)].(map[string]any)
	for _, name := range slices.Sorted(maps.Keys(entries)) {
		secret := &entity.Secret{}
		if err := decodeBlock(block, entries[name], secret); err != nil {
			return err
		}
		if secret.Key == "" {
			secret.Key = name
		}
		if secret.Key != name {
			return invalidBlock(block, "%s: key %q does not match the name it is listed under", name, secret.Key)
		}
		if !base.IsAppRuntimeEnvAllowed(secret.Key) {
			return invalidBlock(block, "%s is reserved for HivePaaS", secret.Key)
		}
		if err := state.addNamedSetting(base.SettingTypeSecret, secret.Key,
			entity.CurrentSecretVersion, false, secret); err != nil {
			return err
		}
	}
	return nil
}

func (s *service) buildConfigFiles(_ context.Context, state *buildState) error {
	block := specmodel.BlockSettingsConfigFiles
	entries, _ := state.req.Doc.Settings[specmodel.CollectionBlockName(base.SettingTypeConfigFile)].(map[string]any)
	for _, name := range slices.Sorted(maps.Keys(entries)) {
		configFile := &entity.ConfigFile{}
		if err := decodeBlock(block, entries[name], configFile); err != nil {
			return err
		}
		if configFile.Name == "" {
			configFile.Name = name
		}
		if configFile.Name != name {
			return invalidBlock(block, "%s: name %q does not match the name it is listed under", name, configFile.Name)
		}
		if err := state.addNamedSetting(base.SettingTypeConfigFile, configFile.Name,
			entity.CurrentConfigFileVersion, false, configFile); err != nil {
			return err
		}
	}
	return nil
}
