package specserviceimpl

import (
	"context"
	"encoding/json"
	"maps"
	"slices"
	"strings"

	"github.com/tiendc/gofn"

	"github.com/hivepaas/hivepaas/hivepaas_app/base"
	"github.com/hivepaas/hivepaas/hivepaas_app/entity"
	"github.com/hivepaas/hivepaas/hivepaas_app/hperrors"
	"github.com/hivepaas/hivepaas/hivepaas_app/pkg/ulid"
	"github.com/hivepaas/hivepaas/hivepaas_app/service/dockerapiservice"
	"github.com/hivepaas/hivepaas/hivepaas_app/service/specservice/specmodel"
)

const maxPort = 65535

func (s *service) buildKind(_ context.Context, state *buildState) error {
	block := specmodel.BlockSettingsKind
	kind := &entity.AppKindSettings{}
	body := state.req.Doc.Settings[specmodel.SingletonBlockName(base.SettingTypeAppKind)]
	if err := decodeBlock(block, body, kind); err != nil {
		return err
	}
	if !slices.Contains(base.AllAppCategories, kind.Category) {
		return invalidBlock(block, "category %q is not one of %v", kind.Category, base.AllAppCategories)
	}
	return state.addSetting(base.SettingTypeAppKind, entity.CurrentAppKindSettingsVersion, false, kind)
}

func (s *service) buildEnvVars(_ context.Context, state *buildState) error {
	block := specmodel.BlockSettingsEnvVars
	envVars := &entity.EnvVars{}
	body := state.req.Doc.Settings[specmodel.SingletonBlockName(base.SettingTypeEnvVar)]
	if err := decodeBlock(block, body, envVars); err != nil {
		return err
	}

	seen := map[string]bool{}
	for i, env := range envVars.Data {
		switch {
		case env == nil || env.Key == "":
			return invalidBlock(block, "data[%d] has no key", i)
		case env.IsSystem:
			return invalidBlock(block, "%s: system variables are generated by HivePaaS, not declared", env.Key)
		case !base.IsAppRuntimeEnvAllowed(env.Key):
			return invalidBlock(block, "%s is reserved for HivePaaS", env.Key)
		case seen[env.Key]:
			return invalidBlock(block, "%s is declared twice", env.Key)
		}
		seen[env.Key] = true
	}
	return state.addSetting(base.SettingTypeEnvVar, entity.CurrentEnvVarsVersion, true, envVars)
}

func (s *service) buildRouting(_ context.Context, state *buildState) error {
	block := specmodel.BlockSettingsRouting
	routing := &entity.AppRoutingSettings{}
	body := state.req.Doc.Settings[specmodel.SingletonBlockName(base.SettingTypeAppRouting)]
	if err := decodeBlock(block, body, routing); err != nil {
		return err
	}
	if routing.Port < 0 || routing.Port > maxPort {
		return invalidBlock(block, "port %d is out of range", routing.Port)
	}
	if err := normalizeRoutingDomains(block, routing); err != nil {
		return err
	}
	return state.addSetting(base.SettingTypeAppRouting, entity.CurrentAppRoutingSettingsVersion, true, routing)
}

// normalizeRoutingDomains drops the domains an app was created without, and
// gives the ones it keeps the port they answer on.
//
// A template names its address through a parameter, and that parameter is
// optional: somebody creating the app before pointing DNS at it leaves it empty,
// and the placeholder resolves to nothing. Dropping the entry here is what lets
// the template say it once, with no condition around it, and still describe both
// cases. An app left with no domain is not exposed publicly either, because
// there is no address for that to mean.
//
// A domain carries its own container port, which a template need not repeat: it
// is the app's port unless that domain answers on a different one. Writing it in
// rather than leaving a zero is what keeps the rest of HivePaaS able to read the
// setting - the routing screen refuses a port below 1, and a zero also reaches
// the resource links as a port nobody listens on.
func normalizeRoutingDomains(block specmodel.Block, routing *entity.AppRoutingSettings) error {
	kept := make([]*entity.AppDomain, 0, len(routing.Domains))
	for i, domain := range routing.Domains {
		if domain == nil || strings.TrimSpace(domain.Domain) == "" {
			continue
		}
		domain.Domain = strings.ToLower(strings.TrimSpace(domain.Domain))
		if strings.HasPrefix(domain.Domain, "*.") {
			return invalidBlock(block, "domains[%d]: %s is what a certificate covers, not an address"+
				" a request arrives at", i, domain.Domain)
		}
		if domain.Protocol == "" {
			domain.Protocol = base.NetworkProtocolHTTP
		}
		if domain.ContainerPort <= 0 {
			domain.ContainerPort = routing.Port
		}
		kept = append(kept, domain)
	}
	routing.Domains = kept
	if len(kept) == 0 {
		routing.ExposePublicly = false
	}
	return nil
}

// buildSecrets and buildConfigFiles build the two collection blocks. Each entry
// is keyed by the name its setting takes, which is also what a secret is
// referred to by - ${THAT_KEY} in an environment variable - and what a config
// file is called. A body may repeat the key, and disagreeing with it is refused
// rather than resolved: one of the two would be silently ignored.
func (s *service) buildSecrets(_ context.Context, state *buildState) error {
	block := specmodel.BlockSettingsSecrets
	entries, _ := state.req.Doc.Settings[specmodel.CollectionBlockName(base.SettingTypeSecret)].(map[string]any)
	for _, name := range slices.Sorted(maps.Keys(entries)) {
		secret := &entity.Secret{}
		body, file, inheritable := templateShorthand(entries[name])
		if err := decodeBlock(block, body, secret); err != nil {
			return err
		}
		if secret.Key == "" {
			secret.Key = name
		}
		if secret.Key != name {
			return invalidBlock(block, "%s: key %q does not match the name it is listed under", name, secret.Key)
		}
		if !base.IsAppRuntimeEnvAllowed(secret.Key) {
			return invalidBlock(block, "%s is reserved for HivePaaS", secret.Key)
		}
		setting, err := state.addNamedSetting(base.SettingTypeSecret, secret.Key,
			entity.CurrentSecretVersion, inheritable, secret)
		if err != nil {
			return err
		}
		if file != nil {
			if err = state.addTemplateMount(block, secret.Key, setting, "value", file, inheritable); err != nil {
				return err
			}
		}
	}
	return nil
}

func (s *service) buildConfigFiles(_ context.Context, state *buildState) error {
	block := specmodel.BlockSettingsConfigFiles
	entries, _ := state.req.Doc.Settings[specmodel.CollectionBlockName(base.SettingTypeConfigFile)].(map[string]any)
	for _, name := range slices.Sorted(maps.Keys(entries)) {
		configFile := &entity.ConfigFile{}
		body, file, inheritable := templateShorthand(entries[name])
		if err := decodeBlock(block, body, configFile); err != nil {
			return err
		}
		if configFile.Name == "" {
			configFile.Name = name
		}
		if configFile.Name != name {
			return invalidBlock(block, "%s: name %q does not match the name it is listed under", name, configFile.Name)
		}
		setting, err := state.addNamedSetting(base.SettingTypeConfigFile, configFile.Name,
			entity.CurrentConfigFileVersion, inheritable, configFile)
		if err != nil {
			return err
		}
		if file != nil {
			if err = state.addTemplateMount(block, configFile.Name, setting, "content", file, inheritable); err != nil {
				return err
			}
		}
	}
	return nil
}

// buildImportedSettings builds every settings block of an exported document. The
// template builders are not used: they check what a template may ask for, and
// an export is what an installation already held.
func (s *service) buildImportedSettings(_ context.Context, state *buildState) error {
	for _, name := range slices.Sorted(maps.Keys(state.req.Doc.Settings)) {
		body := state.req.Doc.Settings[name]
		if typ, ok := specmodel.SingletonTypeOf(name); ok {
			if err := state.addImportedSetting(typ, "", body); err != nil {
				return err
			}
			continue
		}
		typ, ok := specmodel.CollectionTypeOf(name)
		if !ok {
			return hperrors.Wrap(hperrors.ErrSpecBlockUnsupported).WithExtraDetail("settings.%s", name)
		}
		entries, _ := body.(map[string]any)
		for _, key := range slices.Sorted(maps.Keys(entries)) {
			if err := state.addImportedSetting(typ, key, entries[key]); err != nil {
				return err
			}
		}
	}
	return nil
}

// addImportedSetting builds one setting of an exported document: the row from
// what export wrote beside the data, and the data brought to the version this
// installation reads - refused when it is newer. key is a collection entry's
// key, the name when the row names none.
func (state *buildState) addImportedSetting(typ base.SettingType, key string, body any) error {
	block := specmodel.Block("settings." + string(typ))
	setting, parsed, err := decodeImportedSetting(block, typ, key, body)
	if err != nil {
		return err
	}
	setting.ID = gofn.Must(ulid.NewStringULID())
	setting.Scope = base.ObjectScopeApp
	setting.ObjectID = state.req.App.ID
	setting.UpdateVer = 1
	setting.CreatedAt = state.req.TimeNow
	setting.UpdatedAt = state.req.TimeNow
	// Written again through the entity, so a secret that traveled in the clear is
	// encrypted at rest like any other.
	if err = setting.SetData(parsed); err != nil {
		return hperrors.Wrap(err)
	}
	state.settings = append(state.settings, setting)
	return nil
}

// decodeImportedSetting reads one setting body of an exported document: the row
// from what export wrote beside the data, and the data brought to the version
// this installation reads and parsed as its type. The row has no id, scope or
// object: the caller decides where it goes.
func decodeImportedSetting(
	block specmodel.Block, typ base.SettingType, key string, body any,
) (*entity.Setting, entity.SettingData, error) {
	fields, ok := body.(map[string]any)
	if !ok {
		return nil, nil, invalidBlock(block, "%s is not a mapping", key)
	}
	fields = maps.Clone(fields)
	meta := specmodel.SettingMeta{}
	if raw, found := fields[specmodel.SettingMetaKey]; found {
		if err := decodeBlock(block, raw, &meta); err != nil {
			return nil, nil, err
		}
	}
	delete(fields, specmodel.SettingMetaKey)
	delete(fields, specmodel.CollectionEntryIDKey)
	data, err := json.Marshal(fields)
	if err != nil {
		return nil, nil, invalidBlock(block, "%s", err.Error())
	}

	setting := &entity.Setting{
		RefID:       meta.RefID,
		Type:        typ,
		Kind:        meta.Kind,
		Status:      gofn.Coalesce(base.SettingStatus(meta.Status), base.SettingStatusActive),
		Name:        gofn.Coalesce(meta.Name, key),
		Data:        string(data),
		Inheritable: meta.Inheritable,
		Default:     meta.Default,
		Version:     meta.Version,
		ExpireAt:    meta.ExpireAt,
	}
	if _, err = setting.Migrate(); err != nil {
		return nil, nil, hperrors.Wrap(err)
	}
	parsed, err := setting.Parse()
	if err != nil {
		return nil, nil, invalidBlock(block, "%s: %s", key, err.Error())
	}
	return setting, parsed, nil
}

// buildDockerAPI gives the app the Docker API: the setting that says what it may
// do, and on its service, the socket and the network its children join. The
// network is created here because the service is: a spec cannot name one that
// does not exist.
func (s *service) buildDockerAPI(ctx context.Context, state *buildState) error {
	block := specmodel.BlockSettingsDockerAPI
	settings := &entity.AppDockerAPISettings{}
	body := state.req.Doc.Settings[specmodel.SingletonBlockName(base.SettingTypeAppDockerAPI)]
	if err := decodeBlock(block, body, settings); err != nil {
		return err
	}
	networkID, err := s.dockerAPIService.EnsureNetwork(ctx, state.req.App.ID)
	if err != nil {
		return hperrors.Wrap(err)
	}
	dockerapiservice.Attach(state.req.Spec, state.req.App.ID, networkID)
	return state.addSetting(base.SettingTypeAppDockerAPI, entity.CurrentAppDockerAPIVersion, false, settings)
}

// templateShorthand splits a template's secret or config file into the
// setting's own body, its swarmRef.file and its inheritable flag. Templates -
// and only they - may write swarmRef.file: it stands for a setting mount entry
// of the setting (addTemplateMount).
func templateShorthand(entry any) (body, file map[string]any, inheritable bool) {
	fields, ok := entry.(map[string]any)
	if !ok {
		return nil, nil, false
	}
	body = make(map[string]any, len(fields))
	for key, value := range fields {
		switch key {
		case "swarmRef":
			swarmRef, _ := value.(map[string]any)
			file, _ = swarmRef["file"].(map[string]any)
		case "inheritable":
			inheritable, _ = value.(bool)
		default:
			body[key] = value
		}
	}
	return body, file, inheritable
}
