// Code generated by tools/openapi level from docs/openapi/api-level.json. DO NOT EDIT.

package base

// APILevel is the level of the API this server answers. It is raised whenever
// the request of a write operation that already existed changes, and a HivePaaS
// CLI built for a lower level may not write: it would send back objects without
// the fields it does not know. See tools/openapi/level.go.
const APILevel = 1
