// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.35.1
// source: container.proto

package agentproto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ContainerExecReq struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Value:
	//
	//	*ContainerExecReq_Config
	//	*ContainerExecReq_Stdin
	//	*ContainerExecReq_Resize
	Value         isContainerExecReq_Value `protobuf_oneof:"value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContainerExecReq) Reset() {
	*x = ContainerExecReq{}
	mi := &file_container_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContainerExecReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContainerExecReq) ProtoMessage() {}

func (x *ContainerExecReq) ProtoReflect() protoreflect.Message {
	mi := &file_container_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContainerExecReq.ProtoReflect.Descriptor instead.
func (*ContainerExecReq) Descriptor() ([]byte, []int) {
	return file_container_proto_rawDescGZIP(), []int{0}
}

func (x *ContainerExecReq) GetValue() isContainerExecReq_Value {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *ContainerExecReq) GetConfig() *ContainerExecConfig {
	if x != nil {
		if x, ok := x.Value.(*ContainerExecReq_Config); ok {
			return x.Config
		}
	}
	return nil
}

func (x *ContainerExecReq) GetStdin() []byte {
	if x != nil {
		if x, ok := x.Value.(*ContainerExecReq_Stdin); ok {
			return x.Stdin
		}
	}
	return nil
}

func (x *ContainerExecReq) GetResize() *TerminalSize {
	if x != nil {
		if x, ok := x.Value.(*ContainerExecReq_Resize); ok {
			return x.Resize
		}
	}
	return nil
}

type isContainerExecReq_Value interface {
	isContainerExecReq_Value()
}

type ContainerExecReq_Config struct {
	Config *ContainerExecConfig `protobuf:"bytes,1,opt,name=config,proto3,oneof"`
}

type ContainerExecReq_Stdin struct {
	Stdin []byte `protobuf:"bytes,2,opt,name=stdin,proto3,oneof"`
}

type ContainerExecReq_Resize struct {
	Resize *TerminalSize `protobuf:"bytes,3,opt,name=resize,proto3,oneof"`
}

func (*ContainerExecReq_Config) isContainerExecReq_Value() {}

func (*ContainerExecReq_Stdin) isContainerExecReq_Value() {}

func (*ContainerExecReq_Resize) isContainerExecReq_Value() {}

type ContainerExecConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ContainerId   string                 `protobuf:"bytes,1,opt,name=container_id,json=containerId,proto3" json:"container_id,omitempty"`
	Cmd           []string               `protobuf:"bytes,2,rep,name=cmd,proto3" json:"cmd,omitempty"`
	Env           []string               `protobuf:"bytes,3,rep,name=env,proto3" json:"env,omitempty"`
	WorkingDir    string                 `protobuf:"bytes,4,opt,name=working_dir,json=workingDir,proto3" json:"working_dir,omitempty"`
	Tty           bool                   `protobuf:"varint,5,opt,name=tty,proto3" json:"tty,omitempty"`
	ConsoleSize   *TerminalSize          `protobuf:"bytes,6,opt,name=console_size,json=consoleSize,proto3" json:"console_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContainerExecConfig) Reset() {
	*x = ContainerExecConfig{}
	mi := &file_container_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContainerExecConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContainerExecConfig) ProtoMessage() {}

func (x *ContainerExecConfig) ProtoReflect() protoreflect.Message {
	mi := &file_container_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContainerExecConfig.ProtoReflect.Descriptor instead.
func (*ContainerExecConfig) Descriptor() ([]byte, []int) {
	return file_container_proto_rawDescGZIP(), []int{1}
}

func (x *ContainerExecConfig) GetContainerId() string {
	if x != nil {
		return x.ContainerId
	}
	return ""
}

func (x *ContainerExecConfig) GetCmd() []string {
	if x != nil {
		return x.Cmd
	}
	return nil
}

func (x *ContainerExecConfig) GetEnv() []string {
	if x != nil {
		return x.Env
	}
	return nil
}

func (x *ContainerExecConfig) GetWorkingDir() string {
	if x != nil {
		return x.WorkingDir
	}
	return ""
}

func (x *ContainerExecConfig) GetTty() bool {
	if x != nil {
		return x.Tty
	}
	return false
}

func (x *ContainerExecConfig) GetConsoleSize() *TerminalSize {
	if x != nil {
		return x.ConsoleSize
	}
	return nil
}

type TerminalSize struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Width         uint32                 `protobuf:"varint,1,opt,name=width,proto3" json:"width,omitempty"`
	Height        uint32                 `protobuf:"varint,2,opt,name=height,proto3" json:"height,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TerminalSize) Reset() {
	*x = TerminalSize{}
	mi := &file_container_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TerminalSize) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TerminalSize) ProtoMessage() {}

func (x *TerminalSize) ProtoReflect() protoreflect.Message {
	mi := &file_container_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TerminalSize.ProtoReflect.Descriptor instead.
func (*TerminalSize) Descriptor() ([]byte, []int) {
	return file_container_proto_rawDescGZIP(), []int{2}
}

func (x *TerminalSize) GetWidth() uint32 {
	if x != nil {
		return x.Width
	}
	return 0
}

func (x *TerminalSize) GetHeight() uint32 {
	if x != nil {
		return x.Height
	}
	return 0
}

type ContainerExecResp struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Value:
	//
	//	*ContainerExecResp_Stdout
	//	*ContainerExecResp_Stderr
	//	*ContainerExecResp_ExitCode
	Value         isContainerExecResp_Value `protobuf_oneof:"value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContainerExecResp) Reset() {
	*x = ContainerExecResp{}
	mi := &file_container_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContainerExecResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContainerExecResp) ProtoMessage() {}

func (x *ContainerExecResp) ProtoReflect() protoreflect.Message {
	mi := &file_container_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContainerExecResp.ProtoReflect.Descriptor instead.
func (*ContainerExecResp) Descriptor() ([]byte, []int) {
	return file_container_proto_rawDescGZIP(), []int{3}
}

func (x *ContainerExecResp) GetValue() isContainerExecResp_Value {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *ContainerExecResp) GetStdout() []byte {
	if x != nil {
		if x, ok := x.Value.(*ContainerExecResp_Stdout); ok {
			return x.Stdout
		}
	}
	return nil
}

func (x *ContainerExecResp) GetStderr() []byte {
	if x != nil {
		if x, ok := x.Value.(*ContainerExecResp_Stderr); ok {
			return x.Stderr
		}
	}
	return nil
}

func (x *ContainerExecResp) GetExitCode() int32 {
	if x != nil {
		if x, ok := x.Value.(*ContainerExecResp_ExitCode); ok {
			return x.ExitCode
		}
	}
	return 0
}

type isContainerExecResp_Value interface {
	isContainerExecResp_Value()
}

type ContainerExecResp_Stdout struct {
	Stdout []byte `protobuf:"bytes,1,opt,name=stdout,proto3,oneof"`
}

type ContainerExecResp_Stderr struct {
	Stderr []byte `protobuf:"bytes,2,opt,name=stderr,proto3,oneof"`
}

type ContainerExecResp_ExitCode struct {
	ExitCode int32 `protobuf:"varint,3,opt,name=exit_code,json=exitCode,proto3,oneof"`
}

func (*ContainerExecResp_Stdout) isContainerExecResp_Value() {}

func (*ContainerExecResp_Stderr) isContainerExecResp_Value() {}

func (*ContainerExecResp_ExitCode) isContainerExecResp_Value() {}

type ContainerCopyFromReq struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	ContainerId       string                 `protobuf:"bytes,1,opt,name=container_id,json=containerId,proto3" json:"container_id,omitempty"`
	Path              string                 `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	IsDir             bool                   `protobuf:"varint,3,opt,name=is_dir,json=isDir,proto3" json:"is_dir,omitempty"`
	CompressionFormat string                 `protobuf:"bytes,4,opt,name=compression_format,json=compressionFormat,proto3" json:"compression_format,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ContainerCopyFromReq) Reset() {
	*x = ContainerCopyFromReq{}
	mi := &file_container_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContainerCopyFromReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContainerCopyFromReq) ProtoMessage() {}

func (x *ContainerCopyFromReq) ProtoReflect() protoreflect.Message {
	mi := &file_container_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContainerCopyFromReq.ProtoReflect.Descriptor instead.
func (*ContainerCopyFromReq) Descriptor() ([]byte, []int) {
	return file_container_proto_rawDescGZIP(), []int{4}
}

func (x *ContainerCopyFromReq) GetContainerId() string {
	if x != nil {
		return x.ContainerId
	}
	return ""
}

func (x *ContainerCopyFromReq) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *ContainerCopyFromReq) GetIsDir() bool {
	if x != nil {
		return x.IsDir
	}
	return false
}

func (x *ContainerCopyFromReq) GetCompressionFormat() string {
	if x != nil {
		return x.CompressionFormat
	}
	return ""
}

type ContainerCopyFromResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Chunk         []byte                 `protobuf:"bytes,1,opt,name=chunk,proto3" json:"chunk,omitempty"`
	FileName      string                 `protobuf:"bytes,2,opt,name=file_name,json=fileName,proto3" json:"file_name,omitempty"`
	FileSize      int64                  `protobuf:"varint,3,opt,name=file_size,json=fileSize,proto3" json:"file_size,omitempty"`
	ContentType   string                 `protobuf:"bytes,4,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContainerCopyFromResp) Reset() {
	*x = ContainerCopyFromResp{}
	mi := &file_container_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContainerCopyFromResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContainerCopyFromResp) ProtoMessage() {}

func (x *ContainerCopyFromResp) ProtoReflect() protoreflect.Message {
	mi := &file_container_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContainerCopyFromResp.ProtoReflect.Descriptor instead.
func (*ContainerCopyFromResp) Descriptor() ([]byte, []int) {
	return file_container_proto_rawDescGZIP(), []int{5}
}

func (x *ContainerCopyFromResp) GetChunk() []byte {
	if x != nil {
		return x.Chunk
	}
	return nil
}

func (x *ContainerCopyFromResp) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

func (x *ContainerCopyFromResp) GetFileSize() int64 {
	if x != nil {
		return x.FileSize
	}
	return 0
}

func (x *ContainerCopyFromResp) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

var File_container_proto protoreflect.FileDescriptor

const file_container_proto_rawDesc = "" +
	"\n" +
	"\x0fcontainer.proto\x12\x05agent\"\x98\x01\n" +
	"\x10ContainerExecReq\x124\n" +
	"\x06config\x18\x01 \x01(\v2\x1a.agent.ContainerExecConfigH\x00R\x06config\x12\x16\n" +
	"\x05stdin\x18\x02 \x01(\fH\x00R\x05stdin\x12-\n" +
	"\x06resize\x18\x03 \x01(\v2\x13.agent.TerminalSizeH\x00R\x06resizeB\a\n" +
	"\x05value\"\xc7\x01\n" +
	"\x13ContainerExecConfig\x12!\n" +
	"\fcontainer_id\x18\x01 \x01(\tR\vcontainerId\x12\x10\n" +
	"\x03cmd\x18\x02 \x03(\tR\x03cmd\x12\x10\n" +
	"\x03env\x18\x03 \x03(\tR\x03env\x12\x1f\n" +
	"\vworking_dir\x18\x04 \x01(\tR\n" +
	"workingDir\x12\x10\n" +
	"\x03tty\x18\x05 \x01(\bR\x03tty\x126\n" +
	"\fconsole_size\x18\x06 \x01(\v2\x13.agent.TerminalSizeR\vconsoleSize\"<\n" +
	"\fTerminalSize\x12\x14\n" +
	"\x05width\x18\x01 \x01(\rR\x05width\x12\x16\n" +
	"\x06height\x18\x02 \x01(\rR\x06height\"o\n" +
	"\x11ContainerExecResp\x12\x18\n" +
	"\x06stdout\x18\x01 \x01(\fH\x00R\x06stdout\x12\x18\n" +
	"\x06stderr\x18\x02 \x01(\fH\x00R\x06stderr\x12\x1d\n" +
	"\texit_code\x18\x03 \x01(\x05H\x00R\bexitCodeB\a\n" +
	"\x05value\"\x93\x01\n" +
	"\x14ContainerCopyFromReq\x12!\n" +
	"\fcontainer_id\x18\x01 \x01(\tR\vcontainerId\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\x12\x15\n" +
	"\x06is_dir\x18\x03 \x01(\bR\x05isDir\x12-\n" +
	"\x12compression_format\x18\x04 \x01(\tR\x11compressionFormat\"\x8a\x01\n" +
	"\x15ContainerCopyFromResp\x12\x14\n" +
	"\x05chunk\x18\x01 \x01(\fR\x05chunk\x12\x1b\n" +
	"\tfile_name\x18\x02 \x01(\tR\bfileName\x12\x1b\n" +
	"\tfile_size\x18\x03 \x01(\x03R\bfileSize\x12!\n" +
	"\fcontent_type\x18\x04 \x01(\tR\vcontentType2\xac\x01\n" +
	"\x10ContainerService\x12F\n" +
	"\rContainerExec\x12\x17.agent.ContainerExecReq\x1a\x18.agent.ContainerExecResp(\x010\x01\x12P\n" +
	"\x11ContainerCopyFrom\x12\x1b.agent.ContainerCopyFromReq\x1a\x1c.agent.ContainerCopyFromResp0\x01BLZJgithub.com/hivepaas/hivepaas/hivepaas_app/interface/agent/proto;agentprotob\x06proto3"

var (
	file_container_proto_rawDescOnce sync.Once
	file_container_proto_rawDescData []byte
)

func file_container_proto_rawDescGZIP() []byte {
	file_container_proto_rawDescOnce.Do(func() {
		file_container_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_container_proto_rawDesc), len(file_container_proto_rawDesc)))
	})
	return file_container_proto_rawDescData
}

var file_container_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_container_proto_goTypes = []any{
	(*ContainerExecReq)(nil),      // 0: agent.ContainerExecReq
	(*ContainerExecConfig)(nil),   // 1: agent.ContainerExecConfig
	(*TerminalSize)(nil),          // 2: agent.TerminalSize
	(*ContainerExecResp)(nil),     // 3: agent.ContainerExecResp
	(*ContainerCopyFromReq)(nil),  // 4: agent.ContainerCopyFromReq
	(*ContainerCopyFromResp)(nil), // 5: agent.ContainerCopyFromResp
}
var file_container_proto_depIdxs = []int32{
	1, // 0: agent.ContainerExecReq.config:type_name -> agent.ContainerExecConfig
	2, // 1: agent.ContainerExecReq.resize:type_name -> agent.TerminalSize
	2, // 2: agent.ContainerExecConfig.console_size:type_name -> agent.TerminalSize
	0, // 3: agent.ContainerService.ContainerExec:input_type -> agent.ContainerExecReq
	4, // 4: agent.ContainerService.ContainerCopyFrom:input_type -> agent.ContainerCopyFromReq
	3, // 5: agent.ContainerService.ContainerExec:output_type -> agent.ContainerExecResp
	5, // 6: agent.ContainerService.ContainerCopyFrom:output_type -> agent.ContainerCopyFromResp
	5, // [5:7] is the sub-list for method output_type
	3, // [3:5] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_container_proto_init() }
func file_container_proto_init() {
	if File_container_proto != nil {
		return
	}
	file_container_proto_msgTypes[0].OneofWrappers = []any{
		(*ContainerExecReq_Config)(nil),
		(*ContainerExecReq_Stdin)(nil),
		(*ContainerExecReq_Resize)(nil),
	}
	file_container_proto_msgTypes[3].OneofWrappers = []any{
		(*ContainerExecResp_Stdout)(nil),
		(*ContainerExecResp_Stderr)(nil),
		(*ContainerExecResp_ExitCode)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_container_proto_rawDesc), len(file_container_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_container_proto_goTypes,
		DependencyIndexes: file_container_proto_depIdxs,
		MessageInfos:      file_container_proto_msgTypes,
	}.Build()
	File_container_proto = out.File
	file_container_proto_goTypes = nil
	file_container_proto_depIdxs = nil
}
