// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.35.1
// source: docker_api.proto

package agentproto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	DockerAPIService_SyncDockerAPI_FullMethodName      = "/agent.DockerAPIService/SyncDockerAPI"
	DockerAPIService_RemoveDockerAPIApp_FullMethodName = "/agent.DockerAPIService/RemoveDockerAPIApp"
)

// DockerAPIServiceClient is the client API for DockerAPIService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// DockerAPIService is the agent's side of serving apps the Docker API through
// a proxy: every node's agent serves every app that has access.
type DockerAPIServiceClient interface {
	// SyncDockerAPI reads which apps have access and serves exactly those, now
	// rather than at the next tick.
	SyncDockerAPI(ctx context.Context, in *DockerAPISyncReq, opts ...grpc.CallOption) (*DockerAPISyncResp, error)
	// RemoveDockerAPIApp stops serving an app and removes what its children left
	// on the node.
	RemoveDockerAPIApp(ctx context.Context, in *DockerAPIRemoveAppReq, opts ...grpc.CallOption) (*DockerAPIRemoveAppResp, error)
}

type dockerAPIServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDockerAPIServiceClient(cc grpc.ClientConnInterface) DockerAPIServiceClient {
	return &dockerAPIServiceClient{cc}
}

func (c *dockerAPIServiceClient) SyncDockerAPI(ctx context.Context, in *DockerAPISyncReq, opts ...grpc.CallOption) (*DockerAPISyncResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DockerAPISyncResp)
	err := c.cc.Invoke(ctx, DockerAPIService_SyncDockerAPI_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dockerAPIServiceClient) RemoveDockerAPIApp(ctx context.Context, in *DockerAPIRemoveAppReq, opts ...grpc.CallOption) (*DockerAPIRemoveAppResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DockerAPIRemoveAppResp)
	err := c.cc.Invoke(ctx, DockerAPIService_RemoveDockerAPIApp_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DockerAPIServiceServer is the server API for DockerAPIService service.
// All implementations must embed UnimplementedDockerAPIServiceServer
// for forward compatibility.
//
// DockerAPIService is the agent's side of serving apps the Docker API through
// a proxy: every node's agent serves every app that has access.
type DockerAPIServiceServer interface {
	// SyncDockerAPI reads which apps have access and serves exactly those, now
	// rather than at the next tick.
	SyncDockerAPI(context.Context, *DockerAPISyncReq) (*DockerAPISyncResp, error)
	// RemoveDockerAPIApp stops serving an app and removes what its children left
	// on the node.
	RemoveDockerAPIApp(context.Context, *DockerAPIRemoveAppReq) (*DockerAPIRemoveAppResp, error)
	mustEmbedUnimplementedDockerAPIServiceServer()
}

// UnimplementedDockerAPIServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDockerAPIServiceServer struct{}

func (UnimplementedDockerAPIServiceServer) SyncDockerAPI(context.Context, *DockerAPISyncReq) (*DockerAPISyncResp, error) {
	return nil, status.Error(codes.Unimplemented, "method SyncDockerAPI not implemented")
}
func (UnimplementedDockerAPIServiceServer) RemoveDockerAPIApp(context.Context, *DockerAPIRemoveAppReq) (*DockerAPIRemoveAppResp, error) {
	return nil, status.Error(codes.Unimplemented, "method RemoveDockerAPIApp not implemented")
}
func (UnimplementedDockerAPIServiceServer) mustEmbedUnimplementedDockerAPIServiceServer() {}
func (UnimplementedDockerAPIServiceServer) testEmbeddedByValue()                          {}

// UnsafeDockerAPIServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DockerAPIServiceServer will
// result in compilation errors.
type UnsafeDockerAPIServiceServer interface {
	mustEmbedUnimplementedDockerAPIServiceServer()
}

func RegisterDockerAPIServiceServer(s grpc.ServiceRegistrar, srv DockerAPIServiceServer) {
	// If the following call panics, it indicates UnimplementedDockerAPIServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DockerAPIService_ServiceDesc, srv)
}

func _DockerAPIService_SyncDockerAPI_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DockerAPISyncReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DockerAPIServiceServer).SyncDockerAPI(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DockerAPIService_SyncDockerAPI_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DockerAPIServiceServer).SyncDockerAPI(ctx, req.(*DockerAPISyncReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _DockerAPIService_RemoveDockerAPIApp_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DockerAPIRemoveAppReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DockerAPIServiceServer).RemoveDockerAPIApp(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DockerAPIService_RemoveDockerAPIApp_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DockerAPIServiceServer).RemoveDockerAPIApp(ctx, req.(*DockerAPIRemoveAppReq))
	}
	return interceptor(ctx, in, info, handler)
}

// DockerAPIService_ServiceDesc is the grpc.ServiceDesc for DockerAPIService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DockerAPIService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "agent.DockerAPIService",
	HandlerType: (*DockerAPIServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SyncDockerAPI",
			Handler:    _DockerAPIService_SyncDockerAPI_Handler,
		},
		{
			MethodName: "RemoveDockerAPIApp",
			Handler:    _DockerAPIService_RemoveDockerAPIApp_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "docker_api.proto",
}
