// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.35.1
// source: docker_api.proto

package agentproto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DockerAPISyncReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DockerAPISyncReq) Reset() {
	*x = DockerAPISyncReq{}
	mi := &file_docker_api_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DockerAPISyncReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DockerAPISyncReq) ProtoMessage() {}

func (x *DockerAPISyncReq) ProtoReflect() protoreflect.Message {
	mi := &file_docker_api_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DockerAPISyncReq.ProtoReflect.Descriptor instead.
func (*DockerAPISyncReq) Descriptor() ([]byte, []int) {
	return file_docker_api_proto_rawDescGZIP(), []int{0}
}

type DockerAPISyncResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Apps          int32                  `protobuf:"varint,1,opt,name=apps,proto3" json:"apps,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DockerAPISyncResp) Reset() {
	*x = DockerAPISyncResp{}
	mi := &file_docker_api_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DockerAPISyncResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DockerAPISyncResp) ProtoMessage() {}

func (x *DockerAPISyncResp) ProtoReflect() protoreflect.Message {
	mi := &file_docker_api_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DockerAPISyncResp.ProtoReflect.Descriptor instead.
func (*DockerAPISyncResp) Descriptor() ([]byte, []int) {
	return file_docker_api_proto_rawDescGZIP(), []int{1}
}

func (x *DockerAPISyncResp) GetApps() int32 {
	if x != nil {
		return x.Apps
	}
	return 0
}

type DockerAPIRemoveAppReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AppId         string                 `protobuf:"bytes,1,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DockerAPIRemoveAppReq) Reset() {
	*x = DockerAPIRemoveAppReq{}
	mi := &file_docker_api_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DockerAPIRemoveAppReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DockerAPIRemoveAppReq) ProtoMessage() {}

func (x *DockerAPIRemoveAppReq) ProtoReflect() protoreflect.Message {
	mi := &file_docker_api_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DockerAPIRemoveAppReq.ProtoReflect.Descriptor instead.
func (*DockerAPIRemoveAppReq) Descriptor() ([]byte, []int) {
	return file_docker_api_proto_rawDescGZIP(), []int{2}
}

func (x *DockerAPIRemoveAppReq) GetAppId() string {
	if x != nil {
		return x.AppId
	}
	return ""
}

type DockerAPIRemoveAppResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Containers    int32                  `protobuf:"varint,1,opt,name=containers,proto3" json:"containers,omitempty"`
	Networks      int32                  `protobuf:"varint,2,opt,name=networks,proto3" json:"networks,omitempty"`
	Volumes       int32                  `protobuf:"varint,3,opt,name=volumes,proto3" json:"volumes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DockerAPIRemoveAppResp) Reset() {
	*x = DockerAPIRemoveAppResp{}
	mi := &file_docker_api_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DockerAPIRemoveAppResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DockerAPIRemoveAppResp) ProtoMessage() {}

func (x *DockerAPIRemoveAppResp) ProtoReflect() protoreflect.Message {
	mi := &file_docker_api_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DockerAPIRemoveAppResp.ProtoReflect.Descriptor instead.
func (*DockerAPIRemoveAppResp) Descriptor() ([]byte, []int) {
	return file_docker_api_proto_rawDescGZIP(), []int{3}
}

func (x *DockerAPIRemoveAppResp) GetContainers() int32 {
	if x != nil {
		return x.Containers
	}
	return 0
}

func (x *DockerAPIRemoveAppResp) GetNetworks() int32 {
	if x != nil {
		return x.Networks
	}
	return 0
}

func (x *DockerAPIRemoveAppResp) GetVolumes() int32 {
	if x != nil {
		return x.Volumes
	}
	return 0
}

var File_docker_api_proto protoreflect.FileDescriptor

const file_docker_api_proto_rawDesc = "" +
	"\n" +
	"\x10docker_api.proto\x12\x05agent\"\x12\n" +
	"\x10DockerAPISyncReq\"'\n" +
	"\x11DockerAPISyncResp\x12\x12\n" +
	"\x04apps\x18\x01 \x01(\x05R\x04apps\".\n" +
	"\x15DockerAPIRemoveAppReq\x12\x15\n" +
	"\x06app_id\x18\x01 \x01(\tR\x05appId\"n\n" +
	"\x16DockerAPIRemoveAppResp\x12\x1e\n" +
	"\n" +
	"containers\x18\x01 \x01(\x05R\n" +
	"containers\x12\x1a\n" +
	"\bnetworks\x18\x02 \x01(\x05R\bnetworks\x12\x18\n" +
	"\avolumes\x18\x03 \x01(\x05R\avolumes2\xa9\x01\n" +
	"\x10DockerAPIService\x12B\n" +
	"\rSyncDockerAPI\x12\x17.agent.DockerAPISyncReq\x1a\x18.agent.DockerAPISyncResp\x12Q\n" +
	"\x12RemoveDockerAPIApp\x12\x1c.agent.DockerAPIRemoveAppReq\x1a\x1d.agent.DockerAPIRemoveAppRespBLZJgithub.com/hivepaas/hivepaas/hivepaas_app/interface/agent/proto;agentprotob\x06proto3"

var (
	file_docker_api_proto_rawDescOnce sync.Once
	file_docker_api_proto_rawDescData []byte
)

func file_docker_api_proto_rawDescGZIP() []byte {
	file_docker_api_proto_rawDescOnce.Do(func() {
		file_docker_api_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_docker_api_proto_rawDesc), len(file_docker_api_proto_rawDesc)))
	})
	return file_docker_api_proto_rawDescData
}

var file_docker_api_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_docker_api_proto_goTypes = []any{
	(*DockerAPISyncReq)(nil),       // 0: agent.DockerAPISyncReq
	(*DockerAPISyncResp)(nil),      // 1: agent.DockerAPISyncResp
	(*DockerAPIRemoveAppReq)(nil),  // 2: agent.DockerAPIRemoveAppReq
	(*DockerAPIRemoveAppResp)(nil), // 3: agent.DockerAPIRemoveAppResp
}
var file_docker_api_proto_depIdxs = []int32{
	0, // 0: agent.DockerAPIService.SyncDockerAPI:input_type -> agent.DockerAPISyncReq
	2, // 1: agent.DockerAPIService.RemoveDockerAPIApp:input_type -> agent.DockerAPIRemoveAppReq
	1, // 2: agent.DockerAPIService.SyncDockerAPI:output_type -> agent.DockerAPISyncResp
	3, // 3: agent.DockerAPIService.RemoveDockerAPIApp:output_type -> agent.DockerAPIRemoveAppResp
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_docker_api_proto_init() }
func file_docker_api_proto_init() {
	if File_docker_api_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_docker_api_proto_rawDesc), len(file_docker_api_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_docker_api_proto_goTypes,
		DependencyIndexes: file_docker_api_proto_depIdxs,
		MessageInfos:      file_docker_api_proto_msgTypes,
	}.Build()
	File_docker_api_proto = out.File
	file_docker_api_proto_goTypes = nil
	file_docker_api_proto_depIdxs = nil
}
