// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.35.1
// source: file.proto

package agentproto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FileReq struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// root is the volume's directory on the host.
	Root string `protobuf:"bytes,1,opt,name=root,proto3" json:"root,omitempty"`
	// path is inside root.
	Path          string `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileReq) Reset() {
	*x = FileReq{}
	mi := &file_file_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileReq) ProtoMessage() {}

func (x *FileReq) ProtoReflect() protoreflect.Message {
	mi := &file_file_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileReq.ProtoReflect.Descriptor instead.
func (*FileReq) Descriptor() ([]byte, []int) {
	return file_file_proto_rawDescGZIP(), []int{0}
}

func (x *FileReq) GetRoot() string {
	if x != nil {
		return x.Root
	}
	return ""
}

func (x *FileReq) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type FileChunk struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Chunk         []byte                 `protobuf:"bytes,1,opt,name=chunk,proto3" json:"chunk,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileChunk) Reset() {
	*x = FileChunk{}
	mi := &file_file_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileChunk) ProtoMessage() {}

func (x *FileChunk) ProtoReflect() protoreflect.Message {
	mi := &file_file_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileChunk.ProtoReflect.Descriptor instead.
func (*FileChunk) Descriptor() ([]byte, []int) {
	return file_file_proto_rawDescGZIP(), []int{1}
}

func (x *FileChunk) GetChunk() []byte {
	if x != nil {
		return x.Chunk
	}
	return nil
}

type FileWriteReq struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Value:
	//
	//	*FileWriteReq_Target
	//	*FileWriteReq_Chunk
	Value         isFileWriteReq_Value `protobuf_oneof:"value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileWriteReq) Reset() {
	*x = FileWriteReq{}
	mi := &file_file_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileWriteReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileWriteReq) ProtoMessage() {}

func (x *FileWriteReq) ProtoReflect() protoreflect.Message {
	mi := &file_file_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileWriteReq.ProtoReflect.Descriptor instead.
func (*FileWriteReq) Descriptor() ([]byte, []int) {
	return file_file_proto_rawDescGZIP(), []int{2}
}

func (x *FileWriteReq) GetValue() isFileWriteReq_Value {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *FileWriteReq) GetTarget() *FileReq {
	if x != nil {
		if x, ok := x.Value.(*FileWriteReq_Target); ok {
			return x.Target
		}
	}
	return nil
}

func (x *FileWriteReq) GetChunk() []byte {
	if x != nil {
		if x, ok := x.Value.(*FileWriteReq_Chunk); ok {
			return x.Chunk
		}
	}
	return nil
}

type isFileWriteReq_Value interface {
	isFileWriteReq_Value()
}

type FileWriteReq_Target struct {
	Target *FileReq `protobuf:"bytes,1,opt,name=target,proto3,oneof"`
}

type FileWriteReq_Chunk struct {
	Chunk []byte `protobuf:"bytes,2,opt,name=chunk,proto3,oneof"`
}

func (*FileWriteReq_Target) isFileWriteReq_Value() {}

func (*FileWriteReq_Chunk) isFileWriteReq_Value() {}

type FileWriteResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Size          int64                  `protobuf:"varint,1,opt,name=size,proto3" json:"size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileWriteResp) Reset() {
	*x = FileWriteResp{}
	mi := &file_file_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileWriteResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileWriteResp) ProtoMessage() {}

func (x *FileWriteResp) ProtoReflect() protoreflect.Message {
	mi := &file_file_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileWriteResp.ProtoReflect.Descriptor instead.
func (*FileWriteResp) Descriptor() ([]byte, []int) {
	return file_file_proto_rawDescGZIP(), []int{3}
}

func (x *FileWriteResp) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

type FileRemoveResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileRemoveResp) Reset() {
	*x = FileRemoveResp{}
	mi := &file_file_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileRemoveResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileRemoveResp) ProtoMessage() {}

func (x *FileRemoveResp) ProtoReflect() protoreflect.Message {
	mi := &file_file_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileRemoveResp.ProtoReflect.Descriptor instead.
func (*FileRemoveResp) Descriptor() ([]byte, []int) {
	return file_file_proto_rawDescGZIP(), []int{4}
}

type FileStatResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Size          int64                  `protobuf:"varint,1,opt,name=size,proto3" json:"size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileStatResp) Reset() {
	*x = FileStatResp{}
	mi := &file_file_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileStatResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileStatResp) ProtoMessage() {}

func (x *FileStatResp) ProtoReflect() protoreflect.Message {
	mi := &file_file_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileStatResp.ProtoReflect.Descriptor instead.
func (*FileStatResp) Descriptor() ([]byte, []int) {
	return file_file_proto_rawDescGZIP(), []int{5}
}

func (x *FileStatResp) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

var File_file_proto protoreflect.FileDescriptor

const file_file_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"file.proto\x12\x05agent\"1\n" +
	"\aFileReq\x12\x12\n" +
	"\x04root\x18\x01 \x01(\tR\x04root\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\"!\n" +
	"\tFileChunk\x12\x14\n" +
	"\x05chunk\x18\x01 \x01(\fR\x05chunk\"Y\n" +
	"\fFileWriteReq\x12(\n" +
	"\x06target\x18\x01 \x01(\v2\x0e.agent.FileReqH\x00R\x06target\x12\x16\n" +
	"\x05chunk\x18\x02 \x01(\fH\x00R\x05chunkB\a\n" +
	"\x05value\"#\n" +
	"\rFileWriteResp\x12\x12\n" +
	"\x04size\x18\x01 \x01(\x03R\x04size\"\x10\n" +
	"\x0eFileRemoveResp\"\"\n" +
	"\fFileStatResp\x12\x12\n" +
	"\x04size\x18\x01 \x01(\x03R\x04size2\xdd\x01\n" +
	"\vFileService\x12.\n" +
	"\bFileRead\x12\x0e.agent.FileReq\x1a\x10.agent.FileChunk0\x01\x128\n" +
	"\tFileWrite\x12\x13.agent.FileWriteReq\x1a\x14.agent.FileWriteResp(\x01\x123\n" +
	"\n" +
	"FileRemove\x12\x0e.agent.FileReq\x1a\x15.agent.FileRemoveResp\x12/\n" +
	"\bFileStat\x12\x0e.agent.FileReq\x1a\x13.agent.FileStatRespBLZJgithub.com/hivepaas/hivepaas/hivepaas_app/interface/agent/proto;agentprotob\x06proto3"

var (
	file_file_proto_rawDescOnce sync.Once
	file_file_proto_rawDescData []byte
)

func file_file_proto_rawDescGZIP() []byte {
	file_file_proto_rawDescOnce.Do(func() {
		file_file_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_file_proto_rawDesc), len(file_file_proto_rawDesc)))
	})
	return file_file_proto_rawDescData
}

var file_file_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_file_proto_goTypes = []any{
	(*FileReq)(nil),        // 0: agent.FileReq
	(*FileChunk)(nil),      // 1: agent.FileChunk
	(*FileWriteReq)(nil),   // 2: agent.FileWriteReq
	(*FileWriteResp)(nil),  // 3: agent.FileWriteResp
	(*FileRemoveResp)(nil), // 4: agent.FileRemoveResp
	(*FileStatResp)(nil),   // 5: agent.FileStatResp
}
var file_file_proto_depIdxs = []int32{
	0, // 0: agent.FileWriteReq.target:type_name -> agent.FileReq
	0, // 1: agent.FileService.FileRead:input_type -> agent.FileReq
	2, // 2: agent.FileService.FileWrite:input_type -> agent.FileWriteReq
	0, // 3: agent.FileService.FileRemove:input_type -> agent.FileReq
	0, // 4: agent.FileService.FileStat:input_type -> agent.FileReq
	1, // 5: agent.FileService.FileRead:output_type -> agent.FileChunk
	3, // 6: agent.FileService.FileWrite:output_type -> agent.FileWriteResp
	4, // 7: agent.FileService.FileRemove:output_type -> agent.FileRemoveResp
	5, // 8: agent.FileService.FileStat:output_type -> agent.FileStatResp
	5, // [5:9] is the sub-list for method output_type
	1, // [1:5] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_file_proto_init() }
func file_file_proto_init() {
	if File_file_proto != nil {
		return
	}
	file_file_proto_msgTypes[2].OneofWrappers = []any{
		(*FileWriteReq_Target)(nil),
		(*FileWriteReq_Chunk)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_file_proto_rawDesc), len(file_file_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_file_proto_goTypes,
		DependencyIndexes: file_file_proto_depIdxs,
		MessageInfos:      file_file_proto_msgTypes,
	}.Build()
	File_file_proto = out.File
	file_file_proto_goTypes = nil
	file_file_proto_depIdxs = nil
}
