// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.35.1
// source: file.proto

package agentproto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	FileService_FileRead_FullMethodName   = "/agent.FileService/FileRead"
	FileService_FileWrite_FullMethodName  = "/agent.FileService/FileWrite"
	FileService_FileRemove_FullMethodName = "/agent.FileService/FileRemove"
	FileService_FileStat_FullMethodName   = "/agent.FileService/FileStat"
)

// FileServiceClient is the client API for FileService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// FileService reads and writes HivePaaS's files inside a volume's directory on
// this node. A path never leaves the directory it is given in.
type FileServiceClient interface {
	// FileRead streams a file.
	FileRead(ctx context.Context, in *FileReq, opts ...grpc.CallOption) (grpc.ServerStreamingClient[FileChunk], error)
	// FileWrite writes a file: the first message names it, the rest are its
	// content. The file is replaced whole once the stream ends without error.
	FileWrite(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[FileWriteReq, FileWriteResp], error)
	// FileRemove removes a file; one already gone is removed.
	FileRemove(ctx context.Context, in *FileReq, opts ...grpc.CallOption) (*FileRemoveResp, error)
	// FileStat gives a file's size.
	FileStat(ctx context.Context, in *FileReq, opts ...grpc.CallOption) (*FileStatResp, error)
}

type fileServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewFileServiceClient(cc grpc.ClientConnInterface) FileServiceClient {
	return &fileServiceClient{cc}
}

func (c *fileServiceClient) FileRead(ctx context.Context, in *FileReq, opts ...grpc.CallOption) (grpc.ServerStreamingClient[FileChunk], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &FileService_ServiceDesc.Streams[0], FileService_FileRead_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[FileReq, FileChunk]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type FileService_FileReadClient = grpc.ServerStreamingClient[FileChunk]

func (c *fileServiceClient) FileWrite(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[FileWriteReq, FileWriteResp], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &FileService_ServiceDesc.Streams[1], FileService_FileWrite_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[FileWriteReq, FileWriteResp]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type FileService_FileWriteClient = grpc.ClientStreamingClient[FileWriteReq, FileWriteResp]

func (c *fileServiceClient) FileRemove(ctx context.Context, in *FileReq, opts ...grpc.CallOption) (*FileRemoveResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FileRemoveResp)
	err := c.cc.Invoke(ctx, FileService_FileRemove_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fileServiceClient) FileStat(ctx context.Context, in *FileReq, opts ...grpc.CallOption) (*FileStatResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FileStatResp)
	err := c.cc.Invoke(ctx, FileService_FileStat_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FileServiceServer is the server API for FileService service.
// All implementations must embed UnimplementedFileServiceServer
// for forward compatibility.
//
// FileService reads and writes HivePaaS's files inside a volume's directory on
// this node. A path never leaves the directory it is given in.
type FileServiceServer interface {
	// FileRead streams a file.
	FileRead(*FileReq, grpc.ServerStreamingServer[FileChunk]) error
	// FileWrite writes a file: the first message names it, the rest are its
	// content. The file is replaced whole once the stream ends without error.
	FileWrite(grpc.ClientStreamingServer[FileWriteReq, FileWriteResp]) error
	// FileRemove removes a file; one already gone is removed.
	FileRemove(context.Context, *FileReq) (*FileRemoveResp, error)
	// FileStat gives a file's size.
	FileStat(context.Context, *FileReq) (*FileStatResp, error)
	mustEmbedUnimplementedFileServiceServer()
}

// UnimplementedFileServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedFileServiceServer struct{}

func (UnimplementedFileServiceServer) FileRead(*FileReq, grpc.ServerStreamingServer[FileChunk]) error {
	return status.Error(codes.Unimplemented, "method FileRead not implemented")
}
func (UnimplementedFileServiceServer) FileWrite(grpc.ClientStreamingServer[FileWriteReq, FileWriteResp]) error {
	return status.Error(codes.Unimplemented, "method FileWrite not implemented")
}
func (UnimplementedFileServiceServer) FileRemove(context.Context, *FileReq) (*FileRemoveResp, error) {
	return nil, status.Error(codes.Unimplemented, "method FileRemove not implemented")
}
func (UnimplementedFileServiceServer) FileStat(context.Context, *FileReq) (*FileStatResp, error) {
	return nil, status.Error(codes.Unimplemented, "method FileStat not implemented")
}
func (UnimplementedFileServiceServer) mustEmbedUnimplementedFileServiceServer() {}
func (UnimplementedFileServiceServer) testEmbeddedByValue()                     {}

// UnsafeFileServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FileServiceServer will
// result in compilation errors.
type UnsafeFileServiceServer interface {
	mustEmbedUnimplementedFileServiceServer()
}

func RegisterFileServiceServer(s grpc.ServiceRegistrar, srv FileServiceServer) {
	// If the following call panics, it indicates UnimplementedFileServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&FileService_ServiceDesc, srv)
}

func _FileService_FileRead_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(FileReq)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(FileServiceServer).FileRead(m, &grpc.GenericServerStream[FileReq, FileChunk]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type FileService_FileReadServer = grpc.ServerStreamingServer[FileChunk]

func _FileService_FileWrite_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(FileServiceServer).FileWrite(&grpc.GenericServerStream[FileWriteReq, FileWriteResp]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type FileService_FileWriteServer = grpc.ClientStreamingServer[FileWriteReq, FileWriteResp]

func _FileService_FileRemove_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FileReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FileServiceServer).FileRemove(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FileService_FileRemove_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FileServiceServer).FileRemove(ctx, req.(*FileReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _FileService_FileStat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FileReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FileServiceServer).FileStat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FileService_FileStat_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FileServiceServer).FileStat(ctx, req.(*FileReq))
	}
	return interceptor(ctx, in, info, handler)
}

// FileService_ServiceDesc is the grpc.ServiceDesc for FileService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var FileService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "agent.FileService",
	HandlerType: (*FileServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "FileRemove",
			Handler:    _FileService_FileRemove_Handler,
		},
		{
			MethodName: "FileStat",
			Handler:    _FileService_FileStat_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "FileRead",
			Handler:       _FileService_FileRead_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "FileWrite",
			Handler:       _FileService_FileWrite_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "file.proto",
}
