// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.35.1
// source: function.proto

package agentproto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FunctionFile struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Content       string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FunctionFile) Reset() {
	*x = FunctionFile{}
	mi := &file_function_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FunctionFile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FunctionFile) ProtoMessage() {}

func (x *FunctionFile) ProtoReflect() protoreflect.Message {
	mi := &file_function_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FunctionFile.ProtoReflect.Descriptor instead.
func (*FunctionFile) Descriptor() ([]byte, []int) {
	return file_function_proto_rawDescGZIP(), []int{0}
}

func (x *FunctionFile) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *FunctionFile) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

// FunctionValues are the values of one query parameter or header.
type FunctionValues struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Values        []string               `protobuf:"bytes,1,rep,name=values,proto3" json:"values,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FunctionValues) Reset() {
	*x = FunctionValues{}
	mi := &file_function_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FunctionValues) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FunctionValues) ProtoMessage() {}

func (x *FunctionValues) ProtoReflect() protoreflect.Message {
	mi := &file_function_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FunctionValues.ProtoReflect.Descriptor instead.
func (*FunctionValues) Descriptor() ([]byte, []int) {
	return file_function_proto_rawDescGZIP(), []int{1}
}

func (x *FunctionValues) GetValues() []string {
	if x != nil {
		return x.Values
	}
	return nil
}

// FunctionSource is what a test run takes of the function's settings.
type FunctionSource struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Runtime           string                 `protobuf:"bytes,1,opt,name=runtime,proto3" json:"runtime,omitempty"`
	Contract          string                 `protobuf:"bytes,2,opt,name=contract,proto3" json:"contract,omitempty"`
	EntrypointFile    string                 `protobuf:"bytes,3,opt,name=entrypoint_file,json=entrypointFile,proto3" json:"entrypoint_file,omitempty"`
	EntrypointHandler string                 `protobuf:"bytes,4,opt,name=entrypoint_handler,json=entrypointHandler,proto3" json:"entrypoint_handler,omitempty"`
	SystemPackages    []string               `protobuf:"bytes,5,rep,name=system_packages,json=systemPackages,proto3" json:"system_packages,omitempty"`
	TimeoutMs         int64                  `protobuf:"varint,6,opt,name=timeout_ms,json=timeoutMs,proto3" json:"timeout_ms,omitempty"`
	MaxConcurrency    int64                  `protobuf:"varint,7,opt,name=max_concurrency,json=maxConcurrency,proto3" json:"max_concurrency,omitempty"`
	MaxBodySize       int64                  `protobuf:"varint,8,opt,name=max_body_size,json=maxBodySize,proto3" json:"max_body_size,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *FunctionSource) Reset() {
	*x = FunctionSource{}
	mi := &file_function_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FunctionSource) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FunctionSource) ProtoMessage() {}

func (x *FunctionSource) ProtoReflect() protoreflect.Message {
	mi := &file_function_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FunctionSource.ProtoReflect.Descriptor instead.
func (*FunctionSource) Descriptor() ([]byte, []int) {
	return file_function_proto_rawDescGZIP(), []int{2}
}

func (x *FunctionSource) GetRuntime() string {
	if x != nil {
		return x.Runtime
	}
	return ""
}

func (x *FunctionSource) GetContract() string {
	if x != nil {
		return x.Contract
	}
	return ""
}

func (x *FunctionSource) GetEntrypointFile() string {
	if x != nil {
		return x.EntrypointFile
	}
	return ""
}

func (x *FunctionSource) GetEntrypointHandler() string {
	if x != nil {
		return x.EntrypointHandler
	}
	return ""
}

func (x *FunctionSource) GetSystemPackages() []string {
	if x != nil {
		return x.SystemPackages
	}
	return nil
}

func (x *FunctionSource) GetTimeoutMs() int64 {
	if x != nil {
		return x.TimeoutMs
	}
	return 0
}

func (x *FunctionSource) GetMaxConcurrency() int64 {
	if x != nil {
		return x.MaxConcurrency
	}
	return 0
}

func (x *FunctionSource) GetMaxBodySize() int64 {
	if x != nil {
		return x.MaxBodySize
	}
	return 0
}

type FunctionRequest struct {
	state         protoimpl.MessageState     `protogen:"open.v1"`
	Method        string                     `protobuf:"bytes,1,opt,name=method,proto3" json:"method,omitempty"`
	Path          string                     `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	Query         map[string]*FunctionValues `protobuf:"bytes,3,rep,name=query,proto3" json:"query,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Headers       map[string]*FunctionValues `protobuf:"bytes,4,rep,name=headers,proto3" json:"headers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Body          []byte                     `protobuf:"bytes,5,opt,name=body,proto3" json:"body,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FunctionRequest) Reset() {
	*x = FunctionRequest{}
	mi := &file_function_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FunctionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FunctionRequest) ProtoMessage() {}

func (x *FunctionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_function_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FunctionRequest.ProtoReflect.Descriptor instead.
func (*FunctionRequest) Descriptor() ([]byte, []int) {
	return file_function_proto_rawDescGZIP(), []int{3}
}

func (x *FunctionRequest) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *FunctionRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *FunctionRequest) GetQuery() map[string]*FunctionValues {
	if x != nil {
		return x.Query
	}
	return nil
}

func (x *FunctionRequest) GetHeaders() map[string]*FunctionValues {
	if x != nil {
		return x.Headers
	}
	return nil
}

func (x *FunctionRequest) GetBody() []byte {
	if x != nil {
		return x.Body
	}
	return nil
}

type FunctionTestRunReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Source        *FunctionSource        `protobuf:"bytes,1,opt,name=source,proto3" json:"source,omitempty"`
	Files         []*FunctionFile        `protobuf:"bytes,2,rep,name=files,proto3" json:"files,omitempty"`
	Request       *FunctionRequest       `protobuf:"bytes,3,opt,name=request,proto3" json:"request,omitempty"`
	Images        map[string]string      `protobuf:"bytes,4,rep,name=images,proto3" json:"images,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Inputs        *ImageBuildInputs      `protobuf:"bytes,5,opt,name=inputs,proto3" json:"inputs,omitempty"`
	BuildSettings *ImageBuildSettings    `protobuf:"bytes,6,opt,name=build_settings,json=buildSettings,proto3" json:"build_settings,omitempty"` // unset when the app has none
	Env           []string               `protobuf:"bytes,7,rep,name=env,proto3" json:"env,omitempty"`
	Network       string                 `protobuf:"bytes,8,opt,name=network,proto3" json:"network,omitempty"`
	NanoCpus      int64                  `protobuf:"varint,9,opt,name=nano_cpus,json=nanoCpus,proto3" json:"nano_cpus,omitempty"`
	MemoryBytes   int64                  `protobuf:"varint,10,opt,name=memory_bytes,json=memoryBytes,proto3" json:"memory_bytes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FunctionTestRunReq) Reset() {
	*x = FunctionTestRunReq{}
	mi := &file_function_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FunctionTestRunReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FunctionTestRunReq) ProtoMessage() {}

func (x *FunctionTestRunReq) ProtoReflect() protoreflect.Message {
	mi := &file_function_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FunctionTestRunReq.ProtoReflect.Descriptor instead.
func (*FunctionTestRunReq) Descriptor() ([]byte, []int) {
	return file_function_proto_rawDescGZIP(), []int{4}
}

func (x *FunctionTestRunReq) GetSource() *FunctionSource {
	if x != nil {
		return x.Source
	}
	return nil
}

func (x *FunctionTestRunReq) GetFiles() []*FunctionFile {
	if x != nil {
		return x.Files
	}
	return nil
}

func (x *FunctionTestRunReq) GetRequest() *FunctionRequest {
	if x != nil {
		return x.Request
	}
	return nil
}

func (x *FunctionTestRunReq) GetImages() map[string]string {
	if x != nil {
		return x.Images
	}
	return nil
}

func (x *FunctionTestRunReq) GetInputs() *ImageBuildInputs {
	if x != nil {
		return x.Inputs
	}
	return nil
}

func (x *FunctionTestRunReq) GetBuildSettings() *ImageBuildSettings {
	if x != nil {
		return x.BuildSettings
	}
	return nil
}

func (x *FunctionTestRunReq) GetEnv() []string {
	if x != nil {
		return x.Env
	}
	return nil
}

func (x *FunctionTestRunReq) GetNetwork() string {
	if x != nil {
		return x.Network
	}
	return ""
}

func (x *FunctionTestRunReq) GetNanoCpus() int64 {
	if x != nil {
		return x.NanoCpus
	}
	return 0
}

func (x *FunctionTestRunReq) GetMemoryBytes() int64 {
	if x != nil {
		return x.MemoryBytes
	}
	return 0
}

type FunctionTestRunResp struct {
	state          protoimpl.MessageState     `protogen:"open.v1"`
	Outcome        string                     `protobuf:"bytes,1,opt,name=outcome,proto3" json:"outcome,omitempty"`
	Status         int32                      `protobuf:"varint,2,opt,name=status,proto3" json:"status,omitempty"`
	Headers        map[string]*FunctionValues `protobuf:"bytes,3,rep,name=headers,proto3" json:"headers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Body           []byte                     `protobuf:"bytes,4,opt,name=body,proto3" json:"body,omitempty"`
	BodyTruncated  bool                       `protobuf:"varint,5,opt,name=body_truncated,json=bodyTruncated,proto3" json:"body_truncated,omitempty"`
	RequestId      string                     `protobuf:"bytes,6,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	DurationMs     float64                    `protobuf:"fixed64,7,opt,name=duration_ms,json=durationMs,proto3" json:"duration_ms,omitempty"`
	Logs           string                     `protobuf:"bytes,8,opt,name=logs,proto3" json:"logs,omitempty"`
	LogsTruncated  bool                       `protobuf:"varint,9,opt,name=logs_truncated,json=logsTruncated,proto3" json:"logs_truncated,omitempty"`
	Error          string                     `protobuf:"bytes,10,opt,name=error,proto3" json:"error,omitempty"`
	ExitCode       int64                      `protobuf:"varint,11,opt,name=exit_code,json=exitCode,proto3" json:"exit_code,omitempty"`
	LibrariesBuilt bool                       `protobuf:"varint,12,opt,name=libraries_built,json=librariesBuilt,proto3" json:"libraries_built,omitempty"`
	LibrariesLog   string                     `protobuf:"bytes,13,opt,name=libraries_log,json=librariesLog,proto3" json:"libraries_log,omitempty"`
	LockFiles      []*FunctionFile            `protobuf:"bytes,14,rep,name=lock_files,json=lockFiles,proto3" json:"lock_files,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *FunctionTestRunResp) Reset() {
	*x = FunctionTestRunResp{}
	mi := &file_function_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FunctionTestRunResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FunctionTestRunResp) ProtoMessage() {}

func (x *FunctionTestRunResp) ProtoReflect() protoreflect.Message {
	mi := &file_function_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FunctionTestRunResp.ProtoReflect.Descriptor instead.
func (*FunctionTestRunResp) Descriptor() ([]byte, []int) {
	return file_function_proto_rawDescGZIP(), []int{5}
}

func (x *FunctionTestRunResp) GetOutcome() string {
	if x != nil {
		return x.Outcome
	}
	return ""
}

func (x *FunctionTestRunResp) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *FunctionTestRunResp) GetHeaders() map[string]*FunctionValues {
	if x != nil {
		return x.Headers
	}
	return nil
}

func (x *FunctionTestRunResp) GetBody() []byte {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *FunctionTestRunResp) GetBodyTruncated() bool {
	if x != nil {
		return x.BodyTruncated
	}
	return false
}

func (x *FunctionTestRunResp) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *FunctionTestRunResp) GetDurationMs() float64 {
	if x != nil {
		return x.DurationMs
	}
	return 0
}

func (x *FunctionTestRunResp) GetLogs() string {
	if x != nil {
		return x.Logs
	}
	return ""
}

func (x *FunctionTestRunResp) GetLogsTruncated() bool {
	if x != nil {
		return x.LogsTruncated
	}
	return false
}

func (x *FunctionTestRunResp) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *FunctionTestRunResp) GetExitCode() int64 {
	if x != nil {
		return x.ExitCode
	}
	return 0
}

func (x *FunctionTestRunResp) GetLibrariesBuilt() bool {
	if x != nil {
		return x.LibrariesBuilt
	}
	return false
}

func (x *FunctionTestRunResp) GetLibrariesLog() string {
	if x != nil {
		return x.LibrariesLog
	}
	return ""
}

func (x *FunctionTestRunResp) GetLockFiles() []*FunctionFile {
	if x != nil {
		return x.LockFiles
	}
	return nil
}

var File_function_proto protoreflect.FileDescriptor

const file_function_proto_rawDesc = "" +
	"\n" +
	"\x0efunction.proto\x12\x05agent\x1a\x11image_build.proto\"<\n" +
	"\fFunctionFile\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\"(\n" +
	"\x0eFunctionValues\x12\x16\n" +
	"\x06values\x18\x01 \x03(\tR\x06values\"\xb3\x02\n" +
	"\x0eFunctionSource\x12\x18\n" +
	"\aruntime\x18\x01 \x01(\tR\aruntime\x12\x1a\n" +
	"\bcontract\x18\x02 \x01(\tR\bcontract\x12'\n" +
	"\x0fentrypoint_file\x18\x03 \x01(\tR\x0eentrypointFile\x12-\n" +
	"\x12entrypoint_handler\x18\x04 \x01(\tR\x11entrypointHandler\x12'\n" +
	"\x0fsystem_packages\x18\x05 \x03(\tR\x0esystemPackages\x12\x1d\n" +
	"\n" +
	"timeout_ms\x18\x06 \x01(\x03R\ttimeoutMs\x12'\n" +
	"\x0fmax_concurrency\x18\a \x01(\x03R\x0emaxConcurrency\x12\"\n" +
	"\rmax_body_size\x18\b \x01(\x03R\vmaxBodySize\"\xed\x02\n" +
	"\x0fFunctionRequest\x12\x16\n" +
	"\x06method\x18\x01 \x01(\tR\x06method\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\x127\n" +
	"\x05query\x18\x03 \x03(\v2!.agent.FunctionRequest.QueryEntryR\x05query\x12=\n" +
	"\aheaders\x18\x04 \x03(\v2#.agent.FunctionRequest.HeadersEntryR\aheaders\x12\x12\n" +
	"\x04body\x18\x05 \x01(\fR\x04body\x1aO\n" +
	"\n" +
	"QueryEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12+\n" +
	"\x05value\x18\x02 \x01(\v2\x15.agent.FunctionValuesR\x05value:\x028\x01\x1aQ\n" +
	"\fHeadersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12+\n" +
	"\x05value\x18\x02 \x01(\v2\x15.agent.FunctionValuesR\x05value:\x028\x01\"\xf9\x03\n" +
	"\x12FunctionTestRunReq\x12-\n" +
	"\x06source\x18\x01 \x01(\v2\x15.agent.FunctionSourceR\x06source\x12)\n" +
	"\x05files\x18\x02 \x03(\v2\x13.agent.FunctionFileR\x05files\x120\n" +
	"\arequest\x18\x03 \x01(\v2\x16.agent.FunctionRequestR\arequest\x12=\n" +
	"\x06images\x18\x04 \x03(\v2%.agent.FunctionTestRunReq.ImagesEntryR\x06images\x12/\n" +
	"\x06inputs\x18\x05 \x01(\v2\x17.agent.ImageBuildInputsR\x06inputs\x12@\n" +
	"\x0ebuild_settings\x18\x06 \x01(\v2\x19.agent.ImageBuildSettingsR\rbuildSettings\x12\x10\n" +
	"\x03env\x18\a \x03(\tR\x03env\x12\x18\n" +
	"\anetwork\x18\b \x01(\tR\anetwork\x12\x1b\n" +
	"\tnano_cpus\x18\t \x01(\x03R\bnanoCpus\x12!\n" +
	"\fmemory_bytes\x18\n" +
	" \x01(\x03R\vmemoryBytes\x1a9\n" +
	"\vImagesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xc8\x04\n" +
	"\x13FunctionTestRunResp\x12\x18\n" +
	"\aoutcome\x18\x01 \x01(\tR\aoutcome\x12\x16\n" +
	"\x06status\x18\x02 \x01(\x05R\x06status\x12A\n" +
	"\aheaders\x18\x03 \x03(\v2'.agent.FunctionTestRunResp.HeadersEntryR\aheaders\x12\x12\n" +
	"\x04body\x18\x04 \x01(\fR\x04body\x12%\n" +
	"\x0ebody_truncated\x18\x05 \x01(\bR\rbodyTruncated\x12\x1d\n" +
	"\n" +
	"request_id\x18\x06 \x01(\tR\trequestId\x12\x1f\n" +
	"\vduration_ms\x18\a \x01(\x01R\n" +
	"durationMs\x12\x12\n" +
	"\x04logs\x18\b \x01(\tR\x04logs\x12%\n" +
	"\x0elogs_truncated\x18\t \x01(\bR\rlogsTruncated\x12\x14\n" +
	"\x05error\x18\n" +
	" \x01(\tR\x05error\x12\x1b\n" +
	"\texit_code\x18\v \x01(\x03R\bexitCode\x12'\n" +
	"\x0flibraries_built\x18\f \x01(\bR\x0elibrariesBuilt\x12#\n" +
	"\rlibraries_log\x18\r \x01(\tR\flibrariesLog\x122\n" +
	"\n" +
	"lock_files\x18\x0e \x03(\v2\x13.agent.FunctionFileR\tlockFiles\x1aQ\n" +
	"\fHeadersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12+\n" +
	"\x05value\x18\x02 \x01(\v2\x15.agent.FunctionValuesR\x05value:\x028\x012[\n" +
	"\x0fFunctionService\x12H\n" +
	"\x0fFunctionTestRun\x12\x19.agent.FunctionTestRunReq\x1a\x1a.agent.FunctionTestRunRespBLZJgithub.com/hivepaas/hivepaas/hivepaas_app/interface/agent/proto;agentprotob\x06proto3"

var (
	file_function_proto_rawDescOnce sync.Once
	file_function_proto_rawDescData []byte
)

func file_function_proto_rawDescGZIP() []byte {
	file_function_proto_rawDescOnce.Do(func() {
		file_function_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_function_proto_rawDesc), len(file_function_proto_rawDesc)))
	})
	return file_function_proto_rawDescData
}

var file_function_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_function_proto_goTypes = []any{
	(*FunctionFile)(nil),        // 0: agent.FunctionFile
	(*FunctionValues)(nil),      // 1: agent.FunctionValues
	(*FunctionSource)(nil),      // 2: agent.FunctionSource
	(*FunctionRequest)(nil),     // 3: agent.FunctionRequest
	(*FunctionTestRunReq)(nil),  // 4: agent.FunctionTestRunReq
	(*FunctionTestRunResp)(nil), // 5: agent.FunctionTestRunResp
	nil,                         // 6: agent.FunctionRequest.QueryEntry
	nil,                         // 7: agent.FunctionRequest.HeadersEntry
	nil,                         // 8: agent.FunctionTestRunReq.ImagesEntry
	nil,                         // 9: agent.FunctionTestRunResp.HeadersEntry
	(*ImageBuildInputs)(nil),    // 10: agent.ImageBuildInputs
	(*ImageBuildSettings)(nil),  // 11: agent.ImageBuildSettings
}
var file_function_proto_depIdxs = []int32{
	6,  // 0: agent.FunctionRequest.query:type_name -> agent.FunctionRequest.QueryEntry
	7,  // 1: agent.FunctionRequest.headers:type_name -> agent.FunctionRequest.HeadersEntry
	2,  // 2: agent.FunctionTestRunReq.source:type_name -> agent.FunctionSource
	0,  // 3: agent.FunctionTestRunReq.files:type_name -> agent.FunctionFile
	3,  // 4: agent.FunctionTestRunReq.request:type_name -> agent.FunctionRequest
	8,  // 5: agent.FunctionTestRunReq.images:type_name -> agent.FunctionTestRunReq.ImagesEntry
	10, // 6: agent.FunctionTestRunReq.inputs:type_name -> agent.ImageBuildInputs
	11, // 7: agent.FunctionTestRunReq.build_settings:type_name -> agent.ImageBuildSettings
	9,  // 8: agent.FunctionTestRunResp.headers:type_name -> agent.FunctionTestRunResp.HeadersEntry
	0,  // 9: agent.FunctionTestRunResp.lock_files:type_name -> agent.FunctionFile
	1,  // 10: agent.FunctionRequest.QueryEntry.value:type_name -> agent.FunctionValues
	1,  // 11: agent.FunctionRequest.HeadersEntry.value:type_name -> agent.FunctionValues
	1,  // 12: agent.FunctionTestRunResp.HeadersEntry.value:type_name -> agent.FunctionValues
	4,  // 13: agent.FunctionService.FunctionTestRun:input_type -> agent.FunctionTestRunReq
	5,  // 14: agent.FunctionService.FunctionTestRun:output_type -> agent.FunctionTestRunResp
	14, // [14:15] is the sub-list for method output_type
	13, // [13:14] is the sub-list for method input_type
	13, // [13:13] is the sub-list for extension type_name
	13, // [13:13] is the sub-list for extension extendee
	0,  // [0:13] is the sub-list for field type_name
}

func init() { file_function_proto_init() }
func file_function_proto_init() {
	if File_function_proto != nil {
		return
	}
	file_image_build_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_function_proto_rawDesc), len(file_function_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_function_proto_goTypes,
		DependencyIndexes: file_function_proto_depIdxs,
		MessageInfos:      file_function_proto_msgTypes,
	}.Build()
	File_function_proto = out.File
	file_function_proto_goTypes = nil
	file_function_proto_depIdxs = nil
}
