// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.35.1
// source: image_build.proto

package agentproto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ImageBuildReq struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	TaskId             string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	AppId              string                 `protobuf:"bytes,2,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`
	CommitHash         string                 `protobuf:"bytes,3,opt,name=commit_hash,json=commitHash,proto3" json:"commit_hash,omitempty"`
	Dockerfile         *DeploymentDockerfile  `protobuf:"bytes,4,opt,name=dockerfile,proto3" json:"dockerfile,omitempty"`
	ImageName          string                 `protobuf:"bytes,5,opt,name=image_name,json=imageName,proto3" json:"image_name,omitempty"`
	PushToRegistryId   string                 `protobuf:"bytes,6,opt,name=push_to_registry_id,json=pushToRegistryId,proto3" json:"push_to_registry_id,omitempty"`
	ImageBuildSettings *ImageBuildSettings    `protobuf:"bytes,7,opt,name=image_build_settings,json=imageBuildSettings,proto3" json:"image_build_settings,omitempty"`
	NoCache            bool                   `protobuf:"varint,8,opt,name=no_cache,json=noCache,proto3" json:"no_cache,omitempty"`
	BuildId            string                 `protobuf:"bytes,9,opt,name=build_id,json=buildId,proto3" json:"build_id,omitempty"`
	CheckoutDir        string                 `protobuf:"bytes,10,opt,name=checkout_dir,json=checkoutDir,proto3" json:"checkout_dir,omitempty"`
	TempDir            string                 `protobuf:"bytes,11,opt,name=temp_dir,json=tempDir,proto3" json:"temp_dir,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *ImageBuildReq) Reset() {
	*x = ImageBuildReq{}
	mi := &file_image_build_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImageBuildReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImageBuildReq) ProtoMessage() {}

func (x *ImageBuildReq) ProtoReflect() protoreflect.Message {
	mi := &file_image_build_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImageBuildReq.ProtoReflect.Descriptor instead.
func (*ImageBuildReq) Descriptor() ([]byte, []int) {
	return file_image_build_proto_rawDescGZIP(), []int{0}
}

func (x *ImageBuildReq) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *ImageBuildReq) GetAppId() string {
	if x != nil {
		return x.AppId
	}
	return ""
}

func (x *ImageBuildReq) GetCommitHash() string {
	if x != nil {
		return x.CommitHash
	}
	return ""
}

func (x *ImageBuildReq) GetDockerfile() *DeploymentDockerfile {
	if x != nil {
		return x.Dockerfile
	}
	return nil
}

func (x *ImageBuildReq) GetImageName() string {
	if x != nil {
		return x.ImageName
	}
	return ""
}

func (x *ImageBuildReq) GetPushToRegistryId() string {
	if x != nil {
		return x.PushToRegistryId
	}
	return ""
}

func (x *ImageBuildReq) GetImageBuildSettings() *ImageBuildSettings {
	if x != nil {
		return x.ImageBuildSettings
	}
	return nil
}

func (x *ImageBuildReq) GetNoCache() bool {
	if x != nil {
		return x.NoCache
	}
	return false
}

func (x *ImageBuildReq) GetBuildId() string {
	if x != nil {
		return x.BuildId
	}
	return ""
}

func (x *ImageBuildReq) GetCheckoutDir() string {
	if x != nil {
		return x.CheckoutDir
	}
	return ""
}

func (x *ImageBuildReq) GetTempDir() string {
	if x != nil {
		return x.TempDir
	}
	return ""
}

type DeploymentDockerfile struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Source        string                 `protobuf:"bytes,1,opt,name=source,proto3" json:"source,omitempty"`
	Path          string                 `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	Content       string                 `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	ScanPath      string                 `protobuf:"bytes,4,opt,name=scan_path,json=scanPath,proto3" json:"scan_path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeploymentDockerfile) Reset() {
	*x = DeploymentDockerfile{}
	mi := &file_image_build_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeploymentDockerfile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeploymentDockerfile) ProtoMessage() {}

func (x *DeploymentDockerfile) ProtoReflect() protoreflect.Message {
	mi := &file_image_build_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeploymentDockerfile.ProtoReflect.Descriptor instead.
func (*DeploymentDockerfile) Descriptor() ([]byte, []int) {
	return file_image_build_proto_rawDescGZIP(), []int{1}
}

func (x *DeploymentDockerfile) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *DeploymentDockerfile) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *DeploymentDockerfile) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *DeploymentDockerfile) GetScanPath() string {
	if x != nil {
		return x.ScanPath
	}
	return ""
}

type ImageBuildSettings struct {
	state         protoimpl.MessageState      `protogen:"open.v1"`
	Workers       *ImageBuildWorkerSettings   `protobuf:"bytes,1,opt,name=workers,proto3" json:"workers,omitempty"`
	Resources     *ImageBuildResourceSettings `protobuf:"bytes,2,opt,name=resources,proto3" json:"resources,omitempty"`
	Sources       *ImageBuildSourceSettings   `protobuf:"bytes,3,opt,name=sources,proto3" json:"sources,omitempty"`
	NoCache       bool                        `protobuf:"varint,4,opt,name=no_cache,json=noCache,proto3" json:"no_cache,omitempty"`
	NoVerbose     bool                        `protobuf:"varint,5,opt,name=no_verbose,json=noVerbose,proto3" json:"no_verbose,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ImageBuildSettings) Reset() {
	*x = ImageBuildSettings{}
	mi := &file_image_build_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImageBuildSettings) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImageBuildSettings) ProtoMessage() {}

func (x *ImageBuildSettings) ProtoReflect() protoreflect.Message {
	mi := &file_image_build_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImageBuildSettings.ProtoReflect.Descriptor instead.
func (*ImageBuildSettings) Descriptor() ([]byte, []int) {
	return file_image_build_proto_rawDescGZIP(), []int{2}
}

func (x *ImageBuildSettings) GetWorkers() *ImageBuildWorkerSettings {
	if x != nil {
		return x.Workers
	}
	return nil
}

func (x *ImageBuildSettings) GetResources() *ImageBuildResourceSettings {
	if x != nil {
		return x.Resources
	}
	return nil
}

func (x *ImageBuildSettings) GetSources() *ImageBuildSourceSettings {
	if x != nil {
		return x.Sources
	}
	return nil
}

func (x *ImageBuildSettings) GetNoCache() bool {
	if x != nil {
		return x.NoCache
	}
	return false
}

func (x *ImageBuildSettings) GetNoVerbose() bool {
	if x != nil {
		return x.NoVerbose
	}
	return false
}

type ImageBuildWorkerSettings struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	NodeIds        []string               `protobuf:"bytes,1,rep,name=node_ids,json=nodeIds,proto3" json:"node_ids,omitempty"`
	NodeLabels     []string               `protobuf:"bytes,2,rep,name=node_labels,json=nodeLabels,proto3" json:"node_labels,omitempty"`
	MaxParallelism uint32                 `protobuf:"varint,3,opt,name=max_parallelism,json=maxParallelism,proto3" json:"max_parallelism,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ImageBuildWorkerSettings) Reset() {
	*x = ImageBuildWorkerSettings{}
	mi := &file_image_build_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImageBuildWorkerSettings) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImageBuildWorkerSettings) ProtoMessage() {}

func (x *ImageBuildWorkerSettings) ProtoReflect() protoreflect.Message {
	mi := &file_image_build_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImageBuildWorkerSettings.ProtoReflect.Descriptor instead.
func (*ImageBuildWorkerSettings) Descriptor() ([]byte, []int) {
	return file_image_build_proto_rawDescGZIP(), []int{3}
}

func (x *ImageBuildWorkerSettings) GetNodeIds() []string {
	if x != nil {
		return x.NodeIds
	}
	return nil
}

func (x *ImageBuildWorkerSettings) GetNodeLabels() []string {
	if x != nil {
		return x.NodeLabels
	}
	return nil
}

func (x *ImageBuildWorkerSettings) GetMaxParallelism() uint32 {
	if x != nil {
		return x.MaxParallelism
	}
	return 0
}

type ImageBuildResourceSettings struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cpus          uint32                 `protobuf:"varint,1,opt,name=cpus,proto3" json:"cpus,omitempty"`
	Mem           uint64                 `protobuf:"varint,2,opt,name=mem,proto3" json:"mem,omitempty"`
	MemSwap       uint64                 `protobuf:"varint,3,opt,name=mem_swap,json=memSwap,proto3" json:"mem_swap,omitempty"`
	ShmSize       uint64                 `protobuf:"varint,4,opt,name=shm_size,json=shmSize,proto3" json:"shm_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ImageBuildResourceSettings) Reset() {
	*x = ImageBuildResourceSettings{}
	mi := &file_image_build_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImageBuildResourceSettings) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImageBuildResourceSettings) ProtoMessage() {}

func (x *ImageBuildResourceSettings) ProtoReflect() protoreflect.Message {
	mi := &file_image_build_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImageBuildResourceSettings.ProtoReflect.Descriptor instead.
func (*ImageBuildResourceSettings) Descriptor() ([]byte, []int) {
	return file_image_build_proto_rawDescGZIP(), []int{4}
}

func (x *ImageBuildResourceSettings) GetCpus() uint32 {
	if x != nil {
		return x.Cpus
	}
	return 0
}

func (x *ImageBuildResourceSettings) GetMem() uint64 {
	if x != nil {
		return x.Mem
	}
	return 0
}

func (x *ImageBuildResourceSettings) GetMemSwap() uint64 {
	if x != nil {
		return x.MemSwap
	}
	return 0
}

func (x *ImageBuildResourceSettings) GetShmSize() uint64 {
	if x != nil {
		return x.ShmSize
	}
	return 0
}

type ImageBuildSourceSettings struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RepoCache     bool                   `protobuf:"varint,1,opt,name=repo_cache,json=repoCache,proto3" json:"repo_cache,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ImageBuildSourceSettings) Reset() {
	*x = ImageBuildSourceSettings{}
	mi := &file_image_build_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImageBuildSourceSettings) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImageBuildSourceSettings) ProtoMessage() {}

func (x *ImageBuildSourceSettings) ProtoReflect() protoreflect.Message {
	mi := &file_image_build_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImageBuildSourceSettings.ProtoReflect.Descriptor instead.
func (*ImageBuildSourceSettings) Descriptor() ([]byte, []int) {
	return file_image_build_proto_rawDescGZIP(), []int{5}
}

func (x *ImageBuildSourceSettings) GetRepoCache() bool {
	if x != nil {
		return x.RepoCache
	}
	return false
}

type ImageBuildResp struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Value:
	//
	//	*ImageBuildResp_Log
	//	*ImageBuildResp_Result
	Value         isImageBuildResp_Value `protobuf_oneof:"value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ImageBuildResp) Reset() {
	*x = ImageBuildResp{}
	mi := &file_image_build_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImageBuildResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImageBuildResp) ProtoMessage() {}

func (x *ImageBuildResp) ProtoReflect() protoreflect.Message {
	mi := &file_image_build_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImageBuildResp.ProtoReflect.Descriptor instead.
func (*ImageBuildResp) Descriptor() ([]byte, []int) {
	return file_image_build_proto_rawDescGZIP(), []int{6}
}

func (x *ImageBuildResp) GetValue() isImageBuildResp_Value {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *ImageBuildResp) GetLog() *LogFrame {
	if x != nil {
		if x, ok := x.Value.(*ImageBuildResp_Log); ok {
			return x.Log
		}
	}
	return nil
}

func (x *ImageBuildResp) GetResult() *ImageBuildResult {
	if x != nil {
		if x, ok := x.Value.(*ImageBuildResp_Result); ok {
			return x.Result
		}
	}
	return nil
}

type isImageBuildResp_Value interface {
	isImageBuildResp_Value()
}

type ImageBuildResp_Log struct {
	Log *LogFrame `protobuf:"bytes,1,opt,name=log,proto3,oneof"`
}

type ImageBuildResp_Result struct {
	Result *ImageBuildResult `protobuf:"bytes,2,opt,name=result,proto3,oneof"`
}

func (*ImageBuildResp_Log) isImageBuildResp_Value() {}

func (*ImageBuildResp_Result) isImageBuildResp_Value() {}

type LogFrame struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Data          string                 `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	Ts            int64                  `protobuf:"varint,3,opt,name=ts,proto3" json:"ts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogFrame) Reset() {
	*x = LogFrame{}
	mi := &file_image_build_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogFrame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogFrame) ProtoMessage() {}

func (x *LogFrame) ProtoReflect() protoreflect.Message {
	mi := &file_image_build_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogFrame.ProtoReflect.Descriptor instead.
func (*LogFrame) Descriptor() ([]byte, []int) {
	return file_image_build_proto_rawDescGZIP(), []int{7}
}

func (x *LogFrame) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *LogFrame) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

func (x *LogFrame) GetTs() int64 {
	if x != nil {
		return x.Ts
	}
	return 0
}

type ImageBuildResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ImageTags     []string               `protobuf:"bytes,1,rep,name=image_tags,json=imageTags,proto3" json:"image_tags,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ImageBuildResult) Reset() {
	*x = ImageBuildResult{}
	mi := &file_image_build_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImageBuildResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImageBuildResult) ProtoMessage() {}

func (x *ImageBuildResult) ProtoReflect() protoreflect.Message {
	mi := &file_image_build_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImageBuildResult.ProtoReflect.Descriptor instead.
func (*ImageBuildResult) Descriptor() ([]byte, []int) {
	return file_image_build_proto_rawDescGZIP(), []int{8}
}

func (x *ImageBuildResult) GetImageTags() []string {
	if x != nil {
		return x.ImageTags
	}
	return nil
}

var File_image_build_proto protoreflect.FileDescriptor

const file_image_build_proto_rawDesc = "" +
	"\n" +
	"\x11image_build.proto\x12\x05agent\"\xac\x03\n" +
	"\rImageBuildReq\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x15\n" +
	"\x06app_id\x18\x02 \x01(\tR\x05appId\x12\x1f\n" +
	"\vcommit_hash\x18\x03 \x01(\tR\n" +
	"commitHash\x12;\n" +
	"\n" +
	"dockerfile\x18\x04 \x01(\v2\x1b.agent.DeploymentDockerfileR\n" +
	"dockerfile\x12\x1d\n" +
	"\n" +
	"image_name\x18\x05 \x01(\tR\timageName\x12-\n" +
	"\x13push_to_registry_id\x18\x06 \x01(\tR\x10pushToRegistryId\x12K\n" +
	"\x14image_build_settings\x18\a \x01(\v2\x19.agent.ImageBuildSettingsR\x12imageBuildSettings\x12\x19\n" +
	"\bno_cache\x18\b \x01(\bR\anoCache\x12\x19\n" +
	"\bbuild_id\x18\t \x01(\tR\abuildId\x12!\n" +
	"\fcheckout_dir\x18\n" +
	" \x01(\tR\vcheckoutDir\x12\x19\n" +
	"\btemp_dir\x18\v \x01(\tR\atempDir\"y\n" +
	"\x14DeploymentDockerfile\x12\x16\n" +
	"\x06source\x18\x01 \x01(\tR\x06source\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\x12\x18\n" +
	"\acontent\x18\x03 \x01(\tR\acontent\x12\x1b\n" +
	"\tscan_path\x18\x04 \x01(\tR\bscanPath\"\x85\x02\n" +
	"\x12ImageBuildSettings\x129\n" +
	"\aworkers\x18\x01 \x01(\v2\x1f.agent.ImageBuildWorkerSettingsR\aworkers\x12?\n" +
	"\tresources\x18\x02 \x01(\v2!.agent.ImageBuildResourceSettingsR\tresources\x129\n" +
	"\asources\x18\x03 \x01(\v2\x1f.agent.ImageBuildSourceSettingsR\asources\x12\x19\n" +
	"\bno_cache\x18\x04 \x01(\bR\anoCache\x12\x1d\n" +
	"\n" +
	"no_verbose\x18\x05 \x01(\bR\tnoVerbose\"\x7f\n" +
	"\x18ImageBuildWorkerSettings\x12\x19\n" +
	"\bnode_ids\x18\x01 \x03(\tR\anodeIds\x12\x1f\n" +
	"\vnode_labels\x18\x02 \x03(\tR\n" +
	"nodeLabels\x12'\n" +
	"\x0fmax_parallelism\x18\x03 \x01(\rR\x0emaxParallelism\"x\n" +
	"\x1aImageBuildResourceSettings\x12\x12\n" +
	"\x04cpus\x18\x01 \x01(\rR\x04cpus\x12\x10\n" +
	"\x03mem\x18\x02 \x01(\x04R\x03mem\x12\x19\n" +
	"\bmem_swap\x18\x03 \x01(\x04R\amemSwap\x12\x19\n" +
	"\bshm_size\x18\x04 \x01(\x04R\ashmSize\"9\n" +
	"\x18ImageBuildSourceSettings\x12\x1d\n" +
	"\n" +
	"repo_cache\x18\x01 \x01(\bR\trepoCache\"q\n" +
	"\x0eImageBuildResp\x12#\n" +
	"\x03log\x18\x01 \x01(\v2\x0f.agent.LogFrameH\x00R\x03log\x121\n" +
	"\x06result\x18\x02 \x01(\v2\x17.agent.ImageBuildResultH\x00R\x06resultB\a\n" +
	"\x05value\"B\n" +
	"\bLogFrame\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x12\n" +
	"\x04data\x18\x02 \x01(\tR\x04data\x12\x0e\n" +
	"\x02ts\x18\x03 \x01(\x03R\x02ts\"1\n" +
	"\x10ImageBuildResult\x12\x1d\n" +
	"\n" +
	"image_tags\x18\x01 \x03(\tR\timageTags2P\n" +
	"\x11ImageBuildService\x12;\n" +
	"\n" +
	"ImageBuild\x12\x14.agent.ImageBuildReq\x1a\x15.agent.ImageBuildResp0\x01BLZJgithub.com/hivepaas/hivepaas/hivepaas_app/interface/agent/proto;agentprotob\x06proto3"

var (
	file_image_build_proto_rawDescOnce sync.Once
	file_image_build_proto_rawDescData []byte
)

func file_image_build_proto_rawDescGZIP() []byte {
	file_image_build_proto_rawDescOnce.Do(func() {
		file_image_build_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_image_build_proto_rawDesc), len(file_image_build_proto_rawDesc)))
	})
	return file_image_build_proto_rawDescData
}

var file_image_build_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_image_build_proto_goTypes = []any{
	(*ImageBuildReq)(nil),              // 0: agent.ImageBuildReq
	(*DeploymentDockerfile)(nil),       // 1: agent.DeploymentDockerfile
	(*ImageBuildSettings)(nil),         // 2: agent.ImageBuildSettings
	(*ImageBuildWorkerSettings)(nil),   // 3: agent.ImageBuildWorkerSettings
	(*ImageBuildResourceSettings)(nil), // 4: agent.ImageBuildResourceSettings
	(*ImageBuildSourceSettings)(nil),   // 5: agent.ImageBuildSourceSettings
	(*ImageBuildResp)(nil),             // 6: agent.ImageBuildResp
	(*LogFrame)(nil),                   // 7: agent.LogFrame
	(*ImageBuildResult)(nil),           // 8: agent.ImageBuildResult
}
var file_image_build_proto_depIdxs = []int32{
	1, // 0: agent.ImageBuildReq.dockerfile:type_name -> agent.DeploymentDockerfile
	2, // 1: agent.ImageBuildReq.image_build_settings:type_name -> agent.ImageBuildSettings
	3, // 2: agent.ImageBuildSettings.workers:type_name -> agent.ImageBuildWorkerSettings
	4, // 3: agent.ImageBuildSettings.resources:type_name -> agent.ImageBuildResourceSettings
	5, // 4: agent.ImageBuildSettings.sources:type_name -> agent.ImageBuildSourceSettings
	7, // 5: agent.ImageBuildResp.log:type_name -> agent.LogFrame
	8, // 6: agent.ImageBuildResp.result:type_name -> agent.ImageBuildResult
	0, // 7: agent.ImageBuildService.ImageBuild:input_type -> agent.ImageBuildReq
	6, // 8: agent.ImageBuildService.ImageBuild:output_type -> agent.ImageBuildResp
	8, // [8:9] is the sub-list for method output_type
	7, // [7:8] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	7, // [7:7] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file_image_build_proto_init() }
func file_image_build_proto_init() {
	if File_image_build_proto != nil {
		return
	}
	file_image_build_proto_msgTypes[6].OneofWrappers = []any{
		(*ImageBuildResp_Log)(nil),
		(*ImageBuildResp_Result)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_image_build_proto_rawDesc), len(file_image_build_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_image_build_proto_goTypes,
		DependencyIndexes: file_image_build_proto_depIdxs,
		MessageInfos:      file_image_build_proto_msgTypes,
	}.Build()
	File_image_build_proto = out.File
	file_image_build_proto_goTypes = nil
	file_image_build_proto_depIdxs = nil
}
