// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.35.1
// source: image_build.proto

package agentproto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ImageBuildService_ImageBuild_FullMethodName = "/agent.ImageBuildService/ImageBuild"
)

// ImageBuildServiceClient is the client API for ImageBuildService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ImageBuildServiceClient interface {
	ImageBuild(ctx context.Context, in *ImageBuildReq, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ImageBuildResp], error)
}

type imageBuildServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewImageBuildServiceClient(cc grpc.ClientConnInterface) ImageBuildServiceClient {
	return &imageBuildServiceClient{cc}
}

func (c *imageBuildServiceClient) ImageBuild(ctx context.Context, in *ImageBuildReq, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ImageBuildResp], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ImageBuildService_ServiceDesc.Streams[0], ImageBuildService_ImageBuild_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ImageBuildReq, ImageBuildResp]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ImageBuildService_ImageBuildClient = grpc.ServerStreamingClient[ImageBuildResp]

// ImageBuildServiceServer is the server API for ImageBuildService service.
// All implementations must embed UnimplementedImageBuildServiceServer
// for forward compatibility.
type ImageBuildServiceServer interface {
	ImageBuild(*ImageBuildReq, grpc.ServerStreamingServer[ImageBuildResp]) error
	mustEmbedUnimplementedImageBuildServiceServer()
}

// UnimplementedImageBuildServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedImageBuildServiceServer struct{}

func (UnimplementedImageBuildServiceServer) ImageBuild(*ImageBuildReq, grpc.ServerStreamingServer[ImageBuildResp]) error {
	return status.Error(codes.Unimplemented, "method ImageBuild not implemented")
}
func (UnimplementedImageBuildServiceServer) mustEmbedUnimplementedImageBuildServiceServer() {}
func (UnimplementedImageBuildServiceServer) testEmbeddedByValue()                           {}

// UnsafeImageBuildServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ImageBuildServiceServer will
// result in compilation errors.
type UnsafeImageBuildServiceServer interface {
	mustEmbedUnimplementedImageBuildServiceServer()
}

func RegisterImageBuildServiceServer(s grpc.ServiceRegistrar, srv ImageBuildServiceServer) {
	// If the following call panics, it indicates UnimplementedImageBuildServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ImageBuildService_ServiceDesc, srv)
}

func _ImageBuildService_ImageBuild_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ImageBuildReq)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ImageBuildServiceServer).ImageBuild(m, &grpc.GenericServerStream[ImageBuildReq, ImageBuildResp]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ImageBuildService_ImageBuildServer = grpc.ServerStreamingServer[ImageBuildResp]

// ImageBuildService_ServiceDesc is the grpc.ServiceDesc for ImageBuildService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ImageBuildService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "agent.ImageBuildService",
	HandlerType: (*ImageBuildServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ImageBuild",
			Handler:       _ImageBuildService_ImageBuild_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "image_build.proto",
}
