// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.35.1
// source: node_cleanup.proto

package agentproto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type NodeCleanupReq struct {
	state             protoimpl.MessageState  `protogen:"open.v1"`
	TaskId            string                  `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	CleanupSettings   *ClusterCleanupSettings `protobuf:"bytes,2,opt,name=cleanup_settings,json=cleanupSettings,proto3" json:"cleanup_settings,omitempty"`
	CleanupContainers int32                   `protobuf:"varint,3,opt,name=cleanup_containers,json=cleanupContainers,proto3" json:"cleanup_containers,omitempty"`
	CleanupImages     int32                   `protobuf:"varint,4,opt,name=cleanup_images,json=cleanupImages,proto3" json:"cleanup_images,omitempty"`
	CleanupVolumes    int32                   `protobuf:"varint,5,opt,name=cleanup_volumes,json=cleanupVolumes,proto3" json:"cleanup_volumes,omitempty"`
	CleanupNetworks   int32                   `protobuf:"varint,6,opt,name=cleanup_networks,json=cleanupNetworks,proto3" json:"cleanup_networks,omitempty"`
	CleanupBuildCache int32                   `protobuf:"varint,7,opt,name=cleanup_build_cache,json=cleanupBuildCache,proto3" json:"cleanup_build_cache,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *NodeCleanupReq) Reset() {
	*x = NodeCleanupReq{}
	mi := &file_node_cleanup_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeCleanupReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeCleanupReq) ProtoMessage() {}

func (x *NodeCleanupReq) ProtoReflect() protoreflect.Message {
	mi := &file_node_cleanup_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeCleanupReq.ProtoReflect.Descriptor instead.
func (*NodeCleanupReq) Descriptor() ([]byte, []int) {
	return file_node_cleanup_proto_rawDescGZIP(), []int{0}
}

func (x *NodeCleanupReq) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *NodeCleanupReq) GetCleanupSettings() *ClusterCleanupSettings {
	if x != nil {
		return x.CleanupSettings
	}
	return nil
}

func (x *NodeCleanupReq) GetCleanupContainers() int32 {
	if x != nil {
		return x.CleanupContainers
	}
	return 0
}

func (x *NodeCleanupReq) GetCleanupImages() int32 {
	if x != nil {
		return x.CleanupImages
	}
	return 0
}

func (x *NodeCleanupReq) GetCleanupVolumes() int32 {
	if x != nil {
		return x.CleanupVolumes
	}
	return 0
}

func (x *NodeCleanupReq) GetCleanupNetworks() int32 {
	if x != nil {
		return x.CleanupNetworks
	}
	return 0
}

func (x *NodeCleanupReq) GetCleanupBuildCache() int32 {
	if x != nil {
		return x.CleanupBuildCache
	}
	return 0
}

type ClusterCleanupSettings struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Enabled             bool                   `protobuf:"varint,1,opt,name=enabled,proto3" json:"enabled,omitempty"`
	GeneralRetention    int64                  `protobuf:"varint,2,opt,name=general_retention,json=generalRetention,proto3" json:"general_retention,omitempty"`
	BuildCacheRetention int64                  `protobuf:"varint,3,opt,name=build_cache_retention,json=buildCacheRetention,proto3" json:"build_cache_retention,omitempty"`
	PruneImages         bool                   `protobuf:"varint,4,opt,name=prune_images,json=pruneImages,proto3" json:"prune_images,omitempty"`
	PruneVolumes        bool                   `protobuf:"varint,5,opt,name=prune_volumes,json=pruneVolumes,proto3" json:"prune_volumes,omitempty"`
	PruneNetworks       bool                   `protobuf:"varint,6,opt,name=prune_networks,json=pruneNetworks,proto3" json:"prune_networks,omitempty"`
	PruneContainers     bool                   `protobuf:"varint,7,opt,name=prune_containers,json=pruneContainers,proto3" json:"prune_containers,omitempty"`
	PruneBuildCache     bool                   `protobuf:"varint,8,opt,name=prune_build_cache,json=pruneBuildCache,proto3" json:"prune_build_cache,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *ClusterCleanupSettings) Reset() {
	*x = ClusterCleanupSettings{}
	mi := &file_node_cleanup_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClusterCleanupSettings) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClusterCleanupSettings) ProtoMessage() {}

func (x *ClusterCleanupSettings) ProtoReflect() protoreflect.Message {
	mi := &file_node_cleanup_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClusterCleanupSettings.ProtoReflect.Descriptor instead.
func (*ClusterCleanupSettings) Descriptor() ([]byte, []int) {
	return file_node_cleanup_proto_rawDescGZIP(), []int{1}
}

func (x *ClusterCleanupSettings) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *ClusterCleanupSettings) GetGeneralRetention() int64 {
	if x != nil {
		return x.GeneralRetention
	}
	return 0
}

func (x *ClusterCleanupSettings) GetBuildCacheRetention() int64 {
	if x != nil {
		return x.BuildCacheRetention
	}
	return 0
}

func (x *ClusterCleanupSettings) GetPruneImages() bool {
	if x != nil {
		return x.PruneImages
	}
	return false
}

func (x *ClusterCleanupSettings) GetPruneVolumes() bool {
	if x != nil {
		return x.PruneVolumes
	}
	return false
}

func (x *ClusterCleanupSettings) GetPruneNetworks() bool {
	if x != nil {
		return x.PruneNetworks
	}
	return false
}

func (x *ClusterCleanupSettings) GetPruneContainers() bool {
	if x != nil {
		return x.PruneContainers
	}
	return false
}

func (x *ClusterCleanupSettings) GetPruneBuildCache() bool {
	if x != nil {
		return x.PruneBuildCache
	}
	return false
}

type NodeCleanupResp struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	NodeId                string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	NodeName              string                 `protobuf:"bytes,2,opt,name=node_name,json=nodeName,proto3" json:"node_name,omitempty"`
	ImagesDeleted         int32                  `protobuf:"varint,3,opt,name=images_deleted,json=imagesDeleted,proto3" json:"images_deleted,omitempty"`
	ImagesPruneError      string                 `protobuf:"bytes,4,opt,name=images_prune_error,json=imagesPruneError,proto3" json:"images_prune_error,omitempty"`
	VolumesDeleted        int32                  `protobuf:"varint,5,opt,name=volumes_deleted,json=volumesDeleted,proto3" json:"volumes_deleted,omitempty"`
	VolumesPruneError     string                 `protobuf:"bytes,6,opt,name=volumes_prune_error,json=volumesPruneError,proto3" json:"volumes_prune_error,omitempty"`
	ContainersDeleted     int32                  `protobuf:"varint,7,opt,name=containers_deleted,json=containersDeleted,proto3" json:"containers_deleted,omitempty"`
	ContainersPruneError  string                 `protobuf:"bytes,8,opt,name=containers_prune_error,json=containersPruneError,proto3" json:"containers_prune_error,omitempty"`
	TempContainersDeleted int32                  `protobuf:"varint,9,opt,name=temp_containers_deleted,json=tempContainersDeleted,proto3" json:"temp_containers_deleted,omitempty"`
	TempServicesDeleted   int32                  `protobuf:"varint,10,opt,name=temp_services_deleted,json=tempServicesDeleted,proto3" json:"temp_services_deleted,omitempty"`
	NetworksDeleted       int32                  `protobuf:"varint,11,opt,name=networks_deleted,json=networksDeleted,proto3" json:"networks_deleted,omitempty"`
	NetworksPruneError    string                 `protobuf:"bytes,12,opt,name=networks_prune_error,json=networksPruneError,proto3" json:"networks_prune_error,omitempty"`
	BuildCachesDeleted    int32                  `protobuf:"varint,13,opt,name=build_caches_deleted,json=buildCachesDeleted,proto3" json:"build_caches_deleted,omitempty"`
	BuildCachesPruneError string                 `protobuf:"bytes,14,opt,name=build_caches_prune_error,json=buildCachesPruneError,proto3" json:"build_caches_prune_error,omitempty"`
	SpaceReclaimed        uint64                 `protobuf:"varint,15,opt,name=space_reclaimed,json=spaceReclaimed,proto3" json:"space_reclaimed,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *NodeCleanupResp) Reset() {
	*x = NodeCleanupResp{}
	mi := &file_node_cleanup_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeCleanupResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeCleanupResp) ProtoMessage() {}

func (x *NodeCleanupResp) ProtoReflect() protoreflect.Message {
	mi := &file_node_cleanup_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeCleanupResp.ProtoReflect.Descriptor instead.
func (*NodeCleanupResp) Descriptor() ([]byte, []int) {
	return file_node_cleanup_proto_rawDescGZIP(), []int{2}
}

func (x *NodeCleanupResp) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *NodeCleanupResp) GetNodeName() string {
	if x != nil {
		return x.NodeName
	}
	return ""
}

func (x *NodeCleanupResp) GetImagesDeleted() int32 {
	if x != nil {
		return x.ImagesDeleted
	}
	return 0
}

func (x *NodeCleanupResp) GetImagesPruneError() string {
	if x != nil {
		return x.ImagesPruneError
	}
	return ""
}

func (x *NodeCleanupResp) GetVolumesDeleted() int32 {
	if x != nil {
		return x.VolumesDeleted
	}
	return 0
}

func (x *NodeCleanupResp) GetVolumesPruneError() string {
	if x != nil {
		return x.VolumesPruneError
	}
	return ""
}

func (x *NodeCleanupResp) GetContainersDeleted() int32 {
	if x != nil {
		return x.ContainersDeleted
	}
	return 0
}

func (x *NodeCleanupResp) GetContainersPruneError() string {
	if x != nil {
		return x.ContainersPruneError
	}
	return ""
}

func (x *NodeCleanupResp) GetTempContainersDeleted() int32 {
	if x != nil {
		return x.TempContainersDeleted
	}
	return 0
}

func (x *NodeCleanupResp) GetTempServicesDeleted() int32 {
	if x != nil {
		return x.TempServicesDeleted
	}
	return 0
}

func (x *NodeCleanupResp) GetNetworksDeleted() int32 {
	if x != nil {
		return x.NetworksDeleted
	}
	return 0
}

func (x *NodeCleanupResp) GetNetworksPruneError() string {
	if x != nil {
		return x.NetworksPruneError
	}
	return ""
}

func (x *NodeCleanupResp) GetBuildCachesDeleted() int32 {
	if x != nil {
		return x.BuildCachesDeleted
	}
	return 0
}

func (x *NodeCleanupResp) GetBuildCachesPruneError() string {
	if x != nil {
		return x.BuildCachesPruneError
	}
	return ""
}

func (x *NodeCleanupResp) GetSpaceReclaimed() uint64 {
	if x != nil {
		return x.SpaceReclaimed
	}
	return 0
}

var File_node_cleanup_proto protoreflect.FileDescriptor

const file_node_cleanup_proto_rawDesc = "" +
	"\n" +
	"\x12node_cleanup.proto\x12\x05agent\"\xcd\x02\n" +
	"\x0eNodeCleanupReq\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12H\n" +
	"\x10cleanup_settings\x18\x02 \x01(\v2\x1d.agent.ClusterCleanupSettingsR\x0fcleanupSettings\x12-\n" +
	"\x12cleanup_containers\x18\x03 \x01(\x05R\x11cleanupContainers\x12%\n" +
	"\x0ecleanup_images\x18\x04 \x01(\x05R\rcleanupImages\x12'\n" +
	"\x0fcleanup_volumes\x18\x05 \x01(\x05R\x0ecleanupVolumes\x12)\n" +
	"\x10cleanup_networks\x18\x06 \x01(\x05R\x0fcleanupNetworks\x12.\n" +
	"\x13cleanup_build_cache\x18\a \x01(\x05R\x11cleanupBuildCache\"\xd9\x02\n" +
	"\x16ClusterCleanupSettings\x12\x18\n" +
	"\aenabled\x18\x01 \x01(\bR\aenabled\x12+\n" +
	"\x11general_retention\x18\x02 \x01(\x03R\x10generalRetention\x122\n" +
	"\x15build_cache_retention\x18\x03 \x01(\x03R\x13buildCacheRetention\x12!\n" +
	"\fprune_images\x18\x04 \x01(\bR\vpruneImages\x12#\n" +
	"\rprune_volumes\x18\x05 \x01(\bR\fpruneVolumes\x12%\n" +
	"\x0eprune_networks\x18\x06 \x01(\bR\rpruneNetworks\x12)\n" +
	"\x10prune_containers\x18\a \x01(\bR\x0fpruneContainers\x12*\n" +
	"\x11prune_build_cache\x18\b \x01(\bR\x0fpruneBuildCache\"\xb7\x05\n" +
	"\x0fNodeCleanupResp\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x1b\n" +
	"\tnode_name\x18\x02 \x01(\tR\bnodeName\x12%\n" +
	"\x0eimages_deleted\x18\x03 \x01(\x05R\rimagesDeleted\x12,\n" +
	"\x12images_prune_error\x18\x04 \x01(\tR\x10imagesPruneError\x12'\n" +
	"\x0fvolumes_deleted\x18\x05 \x01(\x05R\x0evolumesDeleted\x12.\n" +
	"\x13volumes_prune_error\x18\x06 \x01(\tR\x11volumesPruneError\x12-\n" +
	"\x12containers_deleted\x18\a \x01(\x05R\x11containersDeleted\x124\n" +
	"\x16containers_prune_error\x18\b \x01(\tR\x14containersPruneError\x126\n" +
	"\x17temp_containers_deleted\x18\t \x01(\x05R\x15tempContainersDeleted\x122\n" +
	"\x15temp_services_deleted\x18\n" +
	" \x01(\x05R\x13tempServicesDeleted\x12)\n" +
	"\x10networks_deleted\x18\v \x01(\x05R\x0fnetworksDeleted\x120\n" +
	"\x14networks_prune_error\x18\f \x01(\tR\x12networksPruneError\x120\n" +
	"\x14build_caches_deleted\x18\r \x01(\x05R\x12buildCachesDeleted\x127\n" +
	"\x18build_caches_prune_error\x18\x0e \x01(\tR\x15buildCachesPruneError\x12'\n" +
	"\x0fspace_reclaimed\x18\x0f \x01(\x04R\x0espaceReclaimed2R\n" +
	"\x12NodeCleanupService\x12<\n" +
	"\vNodeCleanup\x12\x15.agent.NodeCleanupReq\x1a\x16.agent.NodeCleanupRespBLZJgithub.com/hivepaas/hivepaas/hivepaas_app/interface/agent/proto;agentprotob\x06proto3"

var (
	file_node_cleanup_proto_rawDescOnce sync.Once
	file_node_cleanup_proto_rawDescData []byte
)

func file_node_cleanup_proto_rawDescGZIP() []byte {
	file_node_cleanup_proto_rawDescOnce.Do(func() {
		file_node_cleanup_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_node_cleanup_proto_rawDesc), len(file_node_cleanup_proto_rawDesc)))
	})
	return file_node_cleanup_proto_rawDescData
}

var file_node_cleanup_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_node_cleanup_proto_goTypes = []any{
	(*NodeCleanupReq)(nil),         // 0: agent.NodeCleanupReq
	(*ClusterCleanupSettings)(nil), // 1: agent.ClusterCleanupSettings
	(*NodeCleanupResp)(nil),        // 2: agent.NodeCleanupResp
}
var file_node_cleanup_proto_depIdxs = []int32{
	1, // 0: agent.NodeCleanupReq.cleanup_settings:type_name -> agent.ClusterCleanupSettings
	0, // 1: agent.NodeCleanupService.NodeCleanup:input_type -> agent.NodeCleanupReq
	2, // 2: agent.NodeCleanupService.NodeCleanup:output_type -> agent.NodeCleanupResp
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_node_cleanup_proto_init() }
func file_node_cleanup_proto_init() {
	if File_node_cleanup_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_node_cleanup_proto_rawDesc), len(file_node_cleanup_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_node_cleanup_proto_goTypes,
		DependencyIndexes: file_node_cleanup_proto_depIdxs,
		MessageInfos:      file_node_cleanup_proto_msgTypes,
	}.Build()
	File_node_cleanup_proto = out.File
	file_node_cleanup_proto_goTypes = nil
	file_node_cleanup_proto_depIdxs = nil
}
