// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.35.1
// source: node_cleanup.proto

package agentproto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	NodeCleanupService_NodeCleanup_FullMethodName = "/agent.NodeCleanupService/NodeCleanup"
)

// NodeCleanupServiceClient is the client API for NodeCleanupService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type NodeCleanupServiceClient interface {
	NodeCleanup(ctx context.Context, in *NodeCleanupReq, opts ...grpc.CallOption) (*NodeCleanupResp, error)
}

type nodeCleanupServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewNodeCleanupServiceClient(cc grpc.ClientConnInterface) NodeCleanupServiceClient {
	return &nodeCleanupServiceClient{cc}
}

func (c *nodeCleanupServiceClient) NodeCleanup(ctx context.Context, in *NodeCleanupReq, opts ...grpc.CallOption) (*NodeCleanupResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NodeCleanupResp)
	err := c.cc.Invoke(ctx, NodeCleanupService_NodeCleanup_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// NodeCleanupServiceServer is the server API for NodeCleanupService service.
// All implementations must embed UnimplementedNodeCleanupServiceServer
// for forward compatibility.
type NodeCleanupServiceServer interface {
	NodeCleanup(context.Context, *NodeCleanupReq) (*NodeCleanupResp, error)
	mustEmbedUnimplementedNodeCleanupServiceServer()
}

// UnimplementedNodeCleanupServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedNodeCleanupServiceServer struct{}

func (UnimplementedNodeCleanupServiceServer) NodeCleanup(context.Context, *NodeCleanupReq) (*NodeCleanupResp, error) {
	return nil, status.Error(codes.Unimplemented, "method NodeCleanup not implemented")
}
func (UnimplementedNodeCleanupServiceServer) mustEmbedUnimplementedNodeCleanupServiceServer() {}
func (UnimplementedNodeCleanupServiceServer) testEmbeddedByValue()                            {}

// UnsafeNodeCleanupServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to NodeCleanupServiceServer will
// result in compilation errors.
type UnsafeNodeCleanupServiceServer interface {
	mustEmbedUnimplementedNodeCleanupServiceServer()
}

func RegisterNodeCleanupServiceServer(s grpc.ServiceRegistrar, srv NodeCleanupServiceServer) {
	// If the following call panics, it indicates UnimplementedNodeCleanupServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&NodeCleanupService_ServiceDesc, srv)
}

func _NodeCleanupService_NodeCleanup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NodeCleanupReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeCleanupServiceServer).NodeCleanup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeCleanupService_NodeCleanup_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeCleanupServiceServer).NodeCleanup(ctx, req.(*NodeCleanupReq))
	}
	return interceptor(ctx, in, info, handler)
}

// NodeCleanupService_ServiceDesc is the grpc.ServiceDesc for NodeCleanupService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var NodeCleanupService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "agent.NodeCleanupService",
	HandlerType: (*NodeCleanupServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "NodeCleanup",
			Handler:    _NodeCleanupService_NodeCleanup_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "node_cleanup.proto",
}
