// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.35.1
// source: repo_server.proto

package agentproto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RepoServerReq struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// repo_path is the repository's directory, as the agent sees the host.
	RepoPath     string `protobuf:"bytes,1,opt,name=repo_path,json=repoPath,proto3" json:"repo_path,omitempty"`
	RepoPassword string `protobuf:"bytes,2,opt,name=repo_password,json=repoPassword,proto3" json:"repo_password,omitempty"`
	// username is the user its clients log in as, user@host.
	Username     string `protobuf:"bytes,3,opt,name=username,proto3" json:"username,omitempty"`
	UserPassword string `protobuf:"bytes,4,opt,name=user_password,json=userPassword,proto3" json:"user_password,omitempty"`
	// listen_host is the agent's address, as the caller reached it.
	ListenHost    string `protobuf:"bytes,5,opt,name=listen_host,json=listenHost,proto3" json:"listen_host,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RepoServerReq) Reset() {
	*x = RepoServerReq{}
	mi := &file_repo_server_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RepoServerReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RepoServerReq) ProtoMessage() {}

func (x *RepoServerReq) ProtoReflect() protoreflect.Message {
	mi := &file_repo_server_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RepoServerReq.ProtoReflect.Descriptor instead.
func (*RepoServerReq) Descriptor() ([]byte, []int) {
	return file_repo_server_proto_rawDescGZIP(), []int{0}
}

func (x *RepoServerReq) GetRepoPath() string {
	if x != nil {
		return x.RepoPath
	}
	return ""
}

func (x *RepoServerReq) GetRepoPassword() string {
	if x != nil {
		return x.RepoPassword
	}
	return ""
}

func (x *RepoServerReq) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *RepoServerReq) GetUserPassword() string {
	if x != nil {
		return x.UserPassword
	}
	return ""
}

func (x *RepoServerReq) GetListenHost() string {
	if x != nil {
		return x.ListenHost
	}
	return ""
}

type RepoServerResp struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Port  int32                  `protobuf:"varint,1,opt,name=port,proto3" json:"port,omitempty"`
	// cert_fingerprint is the SHA-256 fingerprint of the server's certificate.
	CertFingerprint string `protobuf:"bytes,2,opt,name=cert_fingerprint,json=certFingerprint,proto3" json:"cert_fingerprint,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *RepoServerResp) Reset() {
	*x = RepoServerResp{}
	mi := &file_repo_server_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RepoServerResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RepoServerResp) ProtoMessage() {}

func (x *RepoServerResp) ProtoReflect() protoreflect.Message {
	mi := &file_repo_server_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RepoServerResp.ProtoReflect.Descriptor instead.
func (*RepoServerResp) Descriptor() ([]byte, []int) {
	return file_repo_server_proto_rawDescGZIP(), []int{1}
}

func (x *RepoServerResp) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *RepoServerResp) GetCertFingerprint() string {
	if x != nil {
		return x.CertFingerprint
	}
	return ""
}

var File_repo_server_proto protoreflect.FileDescriptor

const file_repo_server_proto_rawDesc = "" +
	"\n" +
	"\x11repo_server.proto\x12\x05agent\"\xb3\x01\n" +
	"\rRepoServerReq\x12\x1b\n" +
	"\trepo_path\x18\x01 \x01(\tR\brepoPath\x12#\n" +
	"\rrepo_password\x18\x02 \x01(\tR\frepoPassword\x12\x1a\n" +
	"\busername\x18\x03 \x01(\tR\busername\x12#\n" +
	"\ruser_password\x18\x04 \x01(\tR\fuserPassword\x12\x1f\n" +
	"\vlisten_host\x18\x05 \x01(\tR\n" +
	"listenHost\"O\n" +
	"\x0eRepoServerResp\x12\x12\n" +
	"\x04port\x18\x01 \x01(\x05R\x04port\x12)\n" +
	"\x10cert_fingerprint\x18\x02 \x01(\tR\x0fcertFingerprint2R\n" +
	"\x11RepoServerService\x12=\n" +
	"\n" +
	"RepoServer\x12\x14.agent.RepoServerReq\x1a\x15.agent.RepoServerResp(\x010\x01BLZJgithub.com/hivepaas/hivepaas/hivepaas_app/interface/agent/proto;agentprotob\x06proto3"

var (
	file_repo_server_proto_rawDescOnce sync.Once
	file_repo_server_proto_rawDescData []byte
)

func file_repo_server_proto_rawDescGZIP() []byte {
	file_repo_server_proto_rawDescOnce.Do(func() {
		file_repo_server_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_repo_server_proto_rawDesc), len(file_repo_server_proto_rawDesc)))
	})
	return file_repo_server_proto_rawDescData
}

var file_repo_server_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_repo_server_proto_goTypes = []any{
	(*RepoServerReq)(nil),  // 0: agent.RepoServerReq
	(*RepoServerResp)(nil), // 1: agent.RepoServerResp
}
var file_repo_server_proto_depIdxs = []int32{
	0, // 0: agent.RepoServerService.RepoServer:input_type -> agent.RepoServerReq
	1, // 1: agent.RepoServerService.RepoServer:output_type -> agent.RepoServerResp
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_repo_server_proto_init() }
func file_repo_server_proto_init() {
	if File_repo_server_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_repo_server_proto_rawDesc), len(file_repo_server_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_repo_server_proto_goTypes,
		DependencyIndexes: file_repo_server_proto_depIdxs,
		MessageInfos:      file_repo_server_proto_msgTypes,
	}.Build()
	File_repo_server_proto = out.File
	file_repo_server_proto_goTypes = nil
	file_repo_server_proto_depIdxs = nil
}
