// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.35.1
// source: repo_server.proto

package agentproto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	RepoServerService_RepoServer_FullMethodName = "/agent.RepoServerService/RepoServer"
)

// RepoServerServiceClient is the client API for RepoServerService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RepoServerServiceClient interface {
	// RepoServer runs a kopia repository server for as long as the stream is open.
	// The client sends one request; the agent answers once the server listens, and
	// ends the stream with an error when the server exits.
	RepoServer(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[RepoServerReq, RepoServerResp], error)
}

type repoServerServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewRepoServerServiceClient(cc grpc.ClientConnInterface) RepoServerServiceClient {
	return &repoServerServiceClient{cc}
}

func (c *repoServerServiceClient) RepoServer(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[RepoServerReq, RepoServerResp], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &RepoServerService_ServiceDesc.Streams[0], RepoServerService_RepoServer_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[RepoServerReq, RepoServerResp]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type RepoServerService_RepoServerClient = grpc.BidiStreamingClient[RepoServerReq, RepoServerResp]

// RepoServerServiceServer is the server API for RepoServerService service.
// All implementations must embed UnimplementedRepoServerServiceServer
// for forward compatibility.
type RepoServerServiceServer interface {
	// RepoServer runs a kopia repository server for as long as the stream is open.
	// The client sends one request; the agent answers once the server listens, and
	// ends the stream with an error when the server exits.
	RepoServer(grpc.BidiStreamingServer[RepoServerReq, RepoServerResp]) error
	mustEmbedUnimplementedRepoServerServiceServer()
}

// UnimplementedRepoServerServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRepoServerServiceServer struct{}

func (UnimplementedRepoServerServiceServer) RepoServer(grpc.BidiStreamingServer[RepoServerReq, RepoServerResp]) error {
	return status.Error(codes.Unimplemented, "method RepoServer not implemented")
}
func (UnimplementedRepoServerServiceServer) mustEmbedUnimplementedRepoServerServiceServer() {}
func (UnimplementedRepoServerServiceServer) testEmbeddedByValue()                           {}

// UnsafeRepoServerServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RepoServerServiceServer will
// result in compilation errors.
type UnsafeRepoServerServiceServer interface {
	mustEmbedUnimplementedRepoServerServiceServer()
}

func RegisterRepoServerServiceServer(s grpc.ServiceRegistrar, srv RepoServerServiceServer) {
	// If the following call panics, it indicates UnimplementedRepoServerServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&RepoServerService_ServiceDesc, srv)
}

func _RepoServerService_RepoServer_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(RepoServerServiceServer).RepoServer(&grpc.GenericServerStream[RepoServerReq, RepoServerResp]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type RepoServerService_RepoServerServer = grpc.BidiStreamingServer[RepoServerReq, RepoServerResp]

// RepoServerService_ServiceDesc is the grpc.ServiceDesc for RepoServerService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RepoServerService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "agent.RepoServerService",
	HandlerType: (*RepoServerServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "RepoServer",
			Handler:       _RepoServerService_RepoServer_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "repo_server.proto",
}
