// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.35.1
// source: volume.proto

package agentproto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RemoveVolumeReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VolumeId      string                 `protobuf:"bytes,1,opt,name=volume_id,json=volumeId,proto3" json:"volume_id,omitempty"`
	Force         bool                   `protobuf:"varint,2,opt,name=force,proto3" json:"force,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveVolumeReq) Reset() {
	*x = RemoveVolumeReq{}
	mi := &file_volume_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveVolumeReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveVolumeReq) ProtoMessage() {}

func (x *RemoveVolumeReq) ProtoReflect() protoreflect.Message {
	mi := &file_volume_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveVolumeReq.ProtoReflect.Descriptor instead.
func (*RemoveVolumeReq) Descriptor() ([]byte, []int) {
	return file_volume_proto_rawDescGZIP(), []int{0}
}

func (x *RemoveVolumeReq) GetVolumeId() string {
	if x != nil {
		return x.VolumeId
	}
	return ""
}

func (x *RemoveVolumeReq) GetForce() bool {
	if x != nil {
		return x.Force
	}
	return false
}

type RemoveVolumeResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveVolumeResp) Reset() {
	*x = RemoveVolumeResp{}
	mi := &file_volume_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveVolumeResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveVolumeResp) ProtoMessage() {}

func (x *RemoveVolumeResp) ProtoReflect() protoreflect.Message {
	mi := &file_volume_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveVolumeResp.ProtoReflect.Descriptor instead.
func (*RemoveVolumeResp) Descriptor() ([]byte, []int) {
	return file_volume_proto_rawDescGZIP(), []int{1}
}

var File_volume_proto protoreflect.FileDescriptor

const file_volume_proto_rawDesc = "" +
	"\n" +
	"\fvolume.proto\x12\x05agent\"D\n" +
	"\x0fRemoveVolumeReq\x12\x1b\n" +
	"\tvolume_id\x18\x01 \x01(\tR\bvolumeId\x12\x14\n" +
	"\x05force\x18\x02 \x01(\bR\x05force\"\x12\n" +
	"\x10RemoveVolumeResp2P\n" +
	"\rVolumeService\x12?\n" +
	"\fRemoveVolume\x12\x16.agent.RemoveVolumeReq\x1a\x17.agent.RemoveVolumeRespBLZJgithub.com/hivepaas/hivepaas/hivepaas_app/interface/agent/proto;agentprotob\x06proto3"

var (
	file_volume_proto_rawDescOnce sync.Once
	file_volume_proto_rawDescData []byte
)

func file_volume_proto_rawDescGZIP() []byte {
	file_volume_proto_rawDescOnce.Do(func() {
		file_volume_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_volume_proto_rawDesc), len(file_volume_proto_rawDesc)))
	})
	return file_volume_proto_rawDescData
}

var file_volume_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_volume_proto_goTypes = []any{
	(*RemoveVolumeReq)(nil),  // 0: agent.RemoveVolumeReq
	(*RemoveVolumeResp)(nil), // 1: agent.RemoveVolumeResp
}
var file_volume_proto_depIdxs = []int32{
	0, // 0: agent.VolumeService.RemoveVolume:input_type -> agent.RemoveVolumeReq
	1, // 1: agent.VolumeService.RemoveVolume:output_type -> agent.RemoveVolumeResp
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_volume_proto_init() }
func file_volume_proto_init() {
	if File_volume_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_volume_proto_rawDesc), len(file_volume_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_volume_proto_goTypes,
		DependencyIndexes: file_volume_proto_depIdxs,
		MessageInfos:      file_volume_proto_msgTypes,
	}.Build()
	File_volume_proto = out.File
	file_volume_proto_goTypes = nil
	file_volume_proto_depIdxs = nil
}
