version: "3"

services:
  frontend:
    image: crccheck/hello-world:latest
    networks:
      - hivepaas_net
      - local_net
    ports:
      - target: 80 # Container port
        published: 8000 # Host port
        protocol: tcp
        mode: host
    logging:
      driver: local
      options:
        max-size: 50m
        compress: "true"

  backend:
    image: crccheck/hello-world:latest
    networks:
      - hivepaas_net
      - local_net
    logging:
      driver: local
      options:
        max-size: 50m
        compress: "true"

  db:
    image: crccheck/hello-world:latest
    networks:
      - hivepaas_net
      - local_net
    logging:
      driver: local
      options:
        max-size: 50m
        compress: "true"

networks:
  hivepaas_net:
    external: true
  local_net:
    driver: overlay
    attachable: true
