version: "3.8"

services:
  traefik:
    image: traefik:v3.7
    command:
      - "--api.insecure=true"
      - "--api.dashboard=true"
      - "--providers.swarm=true"
      - "--providers.swarm.watch=true"
      - "--providers.swarm.network=hivepaas_net"
      - "--providers.swarm.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.web.allowacmebypass=true"
      - "--entrypoints.websecure.address=:443"
      - "--entrypoints.websecure.http.tls=true"
      - "--providers.file.directory=/etc/traefik/dynamic"
      - "--providers.file.watch=true"
      - "--log=true"
      - "--log.level=DEBUG"
      - "--accesslog=true"
    networks:
      # Connect to the 'hivepaas' overlay network for inter-container communication across nodes
      - hivepaas_net
    ports:
      # Expose traefik's entry points to the Swarm
      # Swarm requires the long syntax for ports.
      - target: 80 # Container port
        published: 80 # Host port exposed on the nodes
        protocol: tcp
        # 'host' mode binds directly to the node's IP where the task runs.
        # 'ingress' mode uses Swarm's Routing Mesh (load balances across nodes).
        # Choose based on your load balancing strategy. 'host' is often simpler if using an external LB.
        mode: host
      - target: 443 # Container port
        published: 443 # Host port
        protocol: tcp
        mode: host
      - target: 8080 # Traefik dashboard
        published: 38081 # Exposed dashboard
        protocol: tcp
        mode: host
    volumes:
      - ./hivepaas/traefik/etc/dynamic:/etc/traefik/dynamic
      - ./hivepaas/ssl/certs:/etc/traefik/ssl/certs
      - /var/run/docker.sock:/var/run/docker.sock:ro
    deploy:
      labels:
        - "hivepaas.app.key=traefik"
        - "hivepaas.app.name=traefik"
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
    logging:
      driver: local
      options:
        max-size: 50m
        compress: "true"

  db:
    image: postgres:18-alpine
    networks:
      - local_net
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 3s
      retries: 3
    environment:
      POSTGRES_DB: hivepaas
      POSTGRES_USER: hivepaas
      POSTGRES_PASSWORD: abc123
      PGDATA: /var/lib/postgresql/18/docker
    ports:
      - target: 5432 # Container port
        published: 35432 # Host port exposed on the nodes
        protocol: tcp
        mode: host
    volumes:
      - db:/var/lib/postgresql
    deploy:
      labels:
        - "hivepaas.app.key=db"
        - "hivepaas.app.name=db"
        - "traefik.enable=false"
      mode: replicated
      replicas: 1
    logging:
      driver: local
      options:
        max-size: 50m
        compress: "true"

  redis:
    image: redis:8-alpine
    command: redis-server
    networks:
      - local_net
    ports:
      - target: 6379 # Container port
        published: 36379 # Host port exposed on the nodes
        protocol: tcp
        mode: host
    deploy:
      labels:
        - "hivepaas.app.key=redis"
        - "hivepaas.app.name=redis"
        - "traefik.enable=false"
      mode: replicated
      replicas: 1
    logging:
      driver: local
      options:
        max-size: 50m
        compress: "true"

  adminer:
    image: adminer:latest
    networks:
      - hivepaas_net
      - local_net
    ports:
      - target: 8080 # Container port
        published: 38080 # Host port exposed on the nodes
        protocol: tcp
        mode: host
    deploy:
      labels:
        - "hivepaas.app.key=adminer"
        - "hivepaas.app.name=adminer"
        - "traefik.enable=true"
        - "traefik.http.routers.adminer.rule=Host(`adminer.localhost`)"
        - "traefik.http.routers.adminer.entrypoints=websecure"
        - "traefik.http.routers.adminer.tls=true"
        - "traefik.http.routers.adminer-http.rule=Host(`adminer.localhost`)"
        - "traefik.http.routers.adminer-http.entrypoints=web"
        - "traefik.http.services.adminer.loadbalancer.server.port=8080"
        - "traefik.swarm.network=hivepaas_net"
    logging:
      driver: local
      options:
        max-size: 50m
        compress: "true"

  redis_ui:
    image: redislabs/redisinsight:latest
    networks:
      - local_net
    ports:
      - target: 5540 # Container port
        published: 35540 # Host port exposed on the nodes
        protocol: tcp
        mode: host
    deploy:
      labels:
        - "hivepaas.app.key=redis_ui"
        - "hivepaas.app.name=redis_ui"
        - "traefik.enable=false"
    logging:
      driver: local
      options:
        max-size: 50m
        compress: "true"

  app:
    image: hivepaas/hivepaas-dev:latest
    networks:
      - hivepaas_net
      - local_net
    environment:
      HP_CONFIG_FILE: config/config.development.toml
      HP_USER_ADMIN_USERNAME: admin
      HP_USER_ADMIN_EMAIL: admin@domain.name
      HP_USER_ADMIN_PASSWORD: abc123
      VITE_API_URL: http://localhost:10000
    volumes:
      - ./hivepaas:/var/lib/hivepaas
      - /var/run/docker.sock:/var/run/docker.sock
    deploy:
      labels:
        - "hivepaas.app.key=app"
        - "hivepaas.app.name=app"
        - "traefik.enable=true"
        - "traefik.http.services.app-svc.loadbalancer.server.port=10000"
        - "traefik.http.routers.app-router.rule=Host(`app.dev.localhost`)"
        - "traefik.http.routers.app-router.entrypoints=websecure"
        - "traefik.http.routers.app-router.tls=true"
        - "traefik.http.routers.app-router.service=app-svc"
        - "traefik.http.middlewares.app-router-compress.compress=true"
        - "traefik.http.middlewares.app-router-compress.compress.defaultencoding=br"
        - "traefik.http.middlewares.app-router-compress.compress.minresponsebodybytes=1024"
        - "traefik.http.routers.app-router.middlewares=app-router-compress@swarm"
        - "traefik.http.routers.x-custom-router-acme.rule=PathPrefix(`/.well-known/acme-challenge/`)"
        - "traefik.http.routers.x-custom-router-acme.entrypoints=web"
        - "traefik.http.routers.x-custom-router-acme.tls=false"
        - "traefik.http.middlewares.x-custom-addprefix-acme.addprefix.prefix=/acme"
        - "traefik.http.routers.x-custom-router-acme.middlewares=x-custom-addprefix-acme@swarm"
        - "traefik.swarm.network=hivepaas_net"
      mode: replicated
      replicas: 0
      placement:
        constraints:
          - node.role == manager
    logging:
      driver: local
      options:
        max-size: 50m
        compress: "true"

  worker:
    image: hivepaas/hivepaas-dev:latest
    networks:
      - local_net
    environment:
      HP_CONFIG_FILE: config/config.development.toml
      HP_RUN_MODE: worker
    volumes:
      - ./hivepaas:/var/lib/hivepaas
      - /var/run/docker.sock:/var/run/docker.sock
    deploy:
      labels:
        - "hivepaas.app.key=worker"
        - "hivepaas.app.name=worker"
        - "traefik.enable=false"
      mode: replicated
      replicas: 0
      placement:
        constraints:
          - node.role == manager
    logging:
      driver: local
      options:
        max-size: 50m
        compress: "true"

  updater:
    image: hivepaas/hivepaas-dev:latest
    networks:
      - local_net
    environment:
      HP_CONFIG_FILE: config/config.development.toml
      HP_RUN_MODE: updater
    volumes:
      - ./hivepaas:/var/lib/hivepaas
      - /var/run/docker.sock:/var/run/docker.sock
    deploy:
      labels:
        - "hivepaas.app.key=updater"
        - "hivepaas.app.name=updater"
        - "traefik.enable=false"
      mode: replicated
      replicas: 0
      placement:
        constraints:
          - node.role == manager
    logging:
      driver: local
      options:
        max-size: 50m
        compress: "true"

  agent:
    image: hivepaas/hivepaas-agent-dev:latest
    environment:
      HP_CONFIG_FILE: config/config.development.toml
      HP_AGENT_PORT: "10001"
      HP_AGENT_NODE_ID: "{{.Node.ID}}"
      HP_AGENT_NODE_NAME: "{{.Node.Hostname}}"
      HP_AGENT_SECRET_TOKEN: abc123
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - local_net
    deploy:
      labels:
        - "hivepaas.app.key=agent"
        - "hivepaas.app.name=agent"
        - "traefik.enable=false"
      mode: global
      endpoint_mode: dnsrr
    logging:
      driver: local
      options:
        max-size: 20m
        compress: "true"

# Define the overlay network for Swarm
networks:
  hivepaas_net:
    external: true
  local_net:
    driver: overlay
    attachable: true

volumes:
  db:
    driver: local
